TOML File Format Initial PR
disorderedmaterials/dissolve pull request #1008
Opened 2022-04-04 11:42 UTC by IVlaD17

Closes #899 

First of all I am making it close #899 because we'll be replacing that issue with others that will better define the overall issue.

Secondly, there's two problems with this PR as I am creating this:
- The linting will be all over the place and I'll have to do this manually after making  the PR (please bear with me on that)
- The code within `io.cpp` code that does the outputting at the moment should be put behind a flag/macro.

2022-04-04 12:03 UTC, trisyoungs commented
Do you want me to check this PR out, format it in one go and push it back to make life easier?

2022-04-04 12:10 UTC, IVlaD17 commented
> Do you want me to check this PR out, format it in one go and push it back to make life easier?

That would be an amazing time saver actually. Sadly Visual Studio cannot do that for me.

2022-04-04 12:11 UTC, trisyoungs commented
OK, give me five mins.

2022-04-04 12:14 UTC, trisyoungs commented
OK, just two mins! :)

2022-04-04 13:35 UTC, rprospero requested changes
This is some great work and is looking really nice.  I've got some stylistic things that will help tidy things up a bit, but I'm excited about how well this is coming together.

2022-04-04 13:35 UTC, rprospero commented on src/classes/box.cpp
> +    box["nonPeriodic"] = boxNonPeriodic;
```suggestion
    box["lengths"] = toml::array{a_, b_, c_};
    box["angles"] = toml::array{alpha_, beta_, gamma_};
    box["nonPeriodic"] = toml::array{!periodic_.x, !periodic_.y, !periodic_.z};
```

Shorten the code with fewer variables.

2022-04-04 13:35 UTC, rprospero commented on src/classes/isotopologue.cpp
> +}
Add a newline at the end of the file.

2022-04-04 13:35 UTC, rprospero commented on src/classes/isotopologue.cpp
> +        isotopologue[std::get<0>(isotope).get()->name().data()] = Sears91::A(std::get<1>(isotope));
```suggestion
    for (auto &[type, isotope] : isotopes_)
        isotopologue[type->name().data()] = Sears91::A(isotope);
```

Structured binding for clearer code.

2022-04-04 13:35 UTC, rprospero commented on src/classes/species.cpp
> +            sites[site.get()->name().data()] = site.get()->serialize();
```suggestion
            sites[site->name().data()] = site->serialize();
```

Use shared pointer directly

2022-04-04 13:35 UTC, rprospero commented on src/classes/species.cpp
> +}
newline

2022-04-04 13:35 UTC, rprospero commented on src/classes/speciesangle.cpp
> +            parametersNode[parameters[parameterIndex]] = values[parameterIndex];
Use a range based for-loop

2022-04-04 13:35 UTC, rprospero commented on src/classes/speciesatom.cpp
> +}
newline

2022-04-04 13:35 UTC, rprospero commented on src/classes/speciesbond.cpp
> +            parametersNode[parameters[parameterIndex]] = values[parameterIndex];
range based for loop

2022-04-04 13:35 UTC, rprospero commented on src/classes/speciesimproper.cpp
> +            parametersNode[parameters[parameterIndex]] = values[parameterIndex];
Instead of making another comment about the range based for loop, I'll mention that I think that most of this could be moved into a general `serialize` method on `SpeciesIntra`

2022-04-04 13:35 UTC, rprospero commented on src/classes/speciesimproper.cpp
> +}
\n

2022-04-04 13:35 UTC, rprospero commented on src/classes/speciessite.cpp
> +}
zn

2022-04-04 13:35 UTC, rprospero commented on src/classes/speciestorsion.cpp
> +            parametersNode[parameters[parameterIndex]] = values[parameterIndex];
again

2022-04-04 13:35 UTC, rprospero commented on src/classes/speciestorsion.cpp
> +}
\n

2022-04-04 13:35 UTC, rprospero commented on tests/atomshake/outputfile.toml
> +Test
This probably shouldn't be in the git repo.

2022-04-04 13:35 UTC, rprospero commented on src/main/io.cpp
> +
Hide behind a feature flag.

2022-04-04 13:35 UTC, rprospero commented on src/main/io.cpp
> +        if (coreData_.nMasterBonds() > 0)
```suggestion
        if (!coreData_.nMasterBonds().empty())
```

This occurs a couple of times in the function

2022-04-04 13:36 UTC, rprospero commented
Also, I have a feeling that I'll need to update the flake file at some point so that toml11 gets properly loaded on the CI server.  Just send me a message on team when you're read for me to make the changes.

2022-04-05 10:37 UTC, IVlaD17 commented on src/classes/atomtype.cpp
> +            atomTypeParameters[parameters[parameterIndex]] = values[parameterIndex];
Done.

2022-04-05 10:38 UTC, IVlaD17 commented on CMakeLists.txt
>    find_package(CLI11 REQUIRED)
Done

2022-04-05 10:50 UTC, IVlaD17 commented on src/classes/speciesimproper.cpp
> +            parametersNode[parameters[parameterIndex]] = values[parameterIndex];
I'm going to put this comment as a note in the serialization issue.

2022-04-05 11:01 UTC, IVlaD17 commented on src/main/io.cpp
> +        if (coreData_.nMasterBonds() > 0)
I might be doing something wrong but this suggestion does not seem to work.

2022-04-14 12:31 UTC, rprospero requested changes
I'm suggesting a few more changes before we merge this in.  For my comments about putting in overloads on `toml::into` and `toml::from`, I'm happy with just putting in an issue that makes sure that we come back to that later.

2022-04-14 12:31 UTC, rprospero commented on src/classes/species.cpp
> +        species["forcefield"] = forcefield_->name().data();
If we write an overload to `toml::into` that handles `std::string_view`.  It would make a bunch of the calling code simpler.

2022-04-14 12:31 UTC, rprospero commented on src/classes/species.cpp
> +    if (atoms_.size() > 0)
```suggestion
    if (!atoms_.empty())
```

You'll need this for all the conditions.

The reason for this is that the C++ standard promises that `empty` is always O(1), but `size` can be `O(N)`, depending on the container.  I doubt that we'd move to a container that does that, but it's still good practice to use `empty`.

2022-04-14 12:31 UTC, rprospero commented on src/classes/speciesatom.cpp
> +    atom["r"] = toml::array{r_.x, r_.y, r_.z};
It might also be worth overloading `toml::into` and `toml::from` for `Vec3`.

2022-04-14 12:31 UTC, rprospero commented on src/classes/speciesbond.cpp
> +    if (values.size() > 0)
`empty()`

2022-04-14 12:31 UTC, rprospero commented on src/classes/speciesimproper.cpp
> +    if (values.size() > 0)
`empty`

2022-04-14 12:31 UTC, rprospero commented on src/classes/speciestorsion.cpp
> +    if (values.size() > 0)
`empty`

2022-04-29 16:40 UTC, merged