Add a Pair Potential class wrapper
disorderedmaterials/dissolve pull request #1027
Opened 2022-04-14 16:48 UTC by IVlaD17

Closes #1022 

The `PairPotential` class elements are spread all over the place which makes writing deserializing and serializing code particularly tedious and ugly. This PR adds a class that contains references to all of these elements and this class should set us up to be able to easily transition towards a nicer set-up in the future.

2022-04-19 10:47 UTC, trisyoungs requested changes
Makes sense as a first step in gathering all the pair potential info together.

2022-04-19 10:47 UTC, trisyoungs commented on src/main/dissolve.h
> +    SerializablePairPotential pairPotential_;
This is a bit misleading as named.
```suggestion
    SerializablePairPotential serializablePairPotentials_;
```

2022-04-19 10:47 UTC, trisyoungs commented on src/main/dissolve.cpp
> +      pairPotential_(pairPotentialRange_, pairPotentialDelta_, atomTypeChargeSource_, coreData_.atomTypes())
```suggestion
      serializablePairPotentials_(pairPotentialRange_, pairPotentialDelta_, atomTypeChargeSource_, coreData_.atomTypes())
```

2022-04-19 10:47 UTC, trisyoungs commented on src/classes/serializablepairpotential.cpp
> +#include "serializablepairpotential.h"
Convention in the code is to precede with the subdir name as well. Also needs the license header.
```suggestion
// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2022 Team Dissolve and contributors

#include "classes/serializablepairpotential.h"
```

2022-04-19 10:47 UTC, trisyoungs commented on src/classes/serializablepairpotential.h
> +#pragma once
```suggestion
// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2022 Team Dissolve and contributors

#pragma once
```

2022-04-19 10:47 UTC, trisyoungs commented on windbuild.ps1
> +mkdir build
Custom build script of limited use - should this file really be in the repo?

2022-04-25 07:34 UTC, IVlaD17 commented on windbuild.ps1
> +mkdir build
I tried adding it to .gitignore but it seems that that did not remove the file from the PR. I might need some help there.

2022-04-29 08:33 UTC, trisyoungs approved these changes

2022-04-29 08:54 UTC, merged