Deserialize Species
disorderedmaterials/dissolve pull request #1035
Opened 2022-04-28 13:39 UTC by IVlaD17

Closes #1016 

Dependent on #1008

2022-05-20 10:23 UTC, rprospero reviewed
Some thoughts before this gets reviewed

2022-05-20 10:23 UTC, rprospero commented on src/classes/speciesatom.cpp
> +    if (!node["index"].is_uninitialized())
contains

2022-05-20 10:23 UTC, rprospero commented on src/classes/species.cpp
> +                               if (!bond["i"].is_uninitialized() && !bond["j"].is_uninitialized())
Remove checks and just throw exception

2022-05-20 10:23 UTC, rprospero commented on src/classes/masters.h
> +    std::vector<std::shared_ptr<MasterBond>> masterBonds;
remove redundant `master` name

2022-05-20 10:23 UTC, rprospero commented on src/classes/speciesintra.h
> +    SerialisedValue serialise() const override
Add Comment

2022-05-20 10:23 UTC, rprospero commented on src/classes/speciesintra.h
> +    void deserialise(SerialisedValue &node) override
Add Comment

2022-05-20 10:23 UTC, rprospero commented on src/classes/speciessite.cpp
> +void SpeciesSite::deserialise(SerialisedValue &node)
Use helper functions

2022-05-20 10:23 UTC, rprospero commented on src/main/io.cpp
> +    if (toml_testing_flag)
Remove testing code

2022-05-21 08:02 UTC, trisyoungs requested changes
Looking good!  Just minor comments - bit of `auto` and stuff like that.

2022-05-21 08:02 UTC, trisyoungs commented on src/classes/speciesintra.h
> +            for (int parameterIndex = 0; parameterIndex < values.size(); parameterIndex++)
```suggestion
            for (auto parameterIndex = 0; parameterIndex < values.size(); ++parameterIndex)
```

2022-05-21 08:02 UTC, trisyoungs commented on src/classes/speciestorsion.cpp
> +    SerialisedValue torsion = SpeciesIntra<SpeciesTorsion, TorsionFunctions>::serialise();
```suggestion
    auto torsion = SpeciesIntra<SpeciesTorsion, TorsionFunctions>::serialise();
```

2022-05-23 10:05 UTC, rprospero commented on src/classes/configuration.h
> +    bool read(LineParser &parser, const std::vector<std::unique_ptr<Species>> &availableSpecies, double pairPotentialRange);
Good catch! That's a vestigal bit of code from an *old* commit.  The function doesn't even have an implementation.  I've removed it now.

2022-05-23 11:05 UTC, rprospero commented on src/classes/isotopologue.h
> +    Isotopologue(std::string name);
That is the better way.

2022-05-23 11:09 UTC, rprospero commented on src/classes/masters.h
> +    std::vector<std::shared_ptr<MasterImproper>> impropers;
I thought pretty hard about this.  What I've done is make the Masters class a private inner class of CoreData.  This means that we don't need the ceremony of getters and setters, but we've also indicated that this class should only ever be instantiated within the CoreData class, where it is a private member, giving us the encapsulation we would expect.

2022-05-23 11:25 UTC, rprospero commented on src/classes/masters.h
> +    void deserialise(SerialisedValue &node) override;
I've added the comment to the Masters new location.

2022-05-23 11:26 UTC, rprospero commented on src/classes/species.h
> +    Species(std::string name);
Agreed

2022-05-23 12:54 UTC, trisyoungs approved these changes
:+1:

2022-05-23 15:54 UTC, merged