Deserialize Pair Potentials
disorderedmaterials/dissolve pull request #1039
Opened 2022-05-03 15:20 UTC by IVlaD17

Implemented the `deserialize()` method for the PairPotentials. As part of this PR, I've also added another constructor which I'm fairly sure will change based on other comments. 

Additionally, I changed the node structure to now be `pairPotentials.atomTypes.name` instead of `pairPotentials.name` because TOML bugged out when reading the file without the `atomTypes` node. Doing this required changing the `serialize()` method too.

2022-05-04 08:14 UTC, trisyoungs requested changes
Starting to take shape! Some comments on style and a few other bits.

2022-05-04 08:14 UTC, trisyoungs commented on src/classes/atomtype.cpp
> +    if (!node["z"].is_uninitialized())
Admittedly I may not have been following the TOML conversation as closely as I would have liked lately, but why can't this be written (more nicely) as:
```
    if (node.contains("z"))
```

2022-05-04 08:14 UTC, trisyoungs commented on src/classes/atomtype.cpp
> +void AtomType::deserialize(toml::value node)
Two comments on style here:
1. For consistency, `serialize` and `deserialize` should be the British spelling.
2. I can live with both method definitions being "back-to-back", but there should at the very least be a comment line before the first function to briefly describe the functions that follow.

2022-05-04 08:14 UTC, trisyoungs commented on src/classes/atomtype.cpp
> +        std::vector<std::string> parameters = ShortRangeFunctions::parameters(interactionPotential_.form());
```suggestion
        auto &parameters = ShortRangeFunctions::parameters(interactionPotential_.form());
```

2022-05-04 08:14 UTC, trisyoungs commented on src/classes/atomtype.h
> +    void deserialize(toml::value node);
As with the definitions, need the same comment line describing the purpose of these two functions.

2022-05-04 08:14 UTC, trisyoungs commented on src/classes/serializablepairpotential.cpp
> +            pairPotentials["atomTypes"][atomType->name().data()] = atomType->serialize();
Fairly sure I saw this comment in another PR review somewhere, but line 48 here (checking for the `atomTypes_` vector being `empty()`) is redundant and can be removed.

2022-05-04 08:14 UTC, trisyoungs commented on src/classes/serializablepairpotential.cpp
> +void SerializablePairPotential::deserialize(toml::value node)
Same comments on style as with the `AtomType` routines.

2022-05-04 08:14 UTC, trisyoungs commented on src/main/io.cpp
> +        }
Feels like chunk of code shouldn't be merged in as it's for local testing and is machine specific.

2022-05-04 08:50 UTC, IVlaD17 commented on src/main/io.cpp
> +        }
I'll fix it so it's no longer machine specific.

2022-05-04 08:50 UTC, IVlaD17 commented on src/classes/atomtype.cpp
> +void AtomType::deserialize(toml::value node)
![6euyx3](https://user-images.githubusercontent.com/32511888/166650065-fb5e70f1-fba0-4286-af8b-f60cc5faf183.jpg)

2022-05-04 08:51 UTC, IVlaD17 commented on src/classes/atomtype.cpp
> +void AtomType::deserialize(toml::value node)
I'll begrudgingly do the first and happily do the second.

2022-05-04 09:03 UTC, rprospero commented on src/main/io.cpp
> +        }
The `if` expression does need to be a `constexpr` if we're going to properly make this a feature flag.  However, if we make the filename cross-platform (i.e. putting the toml file in the same directory as the input file), then I would argue that it is useful to leave this in for now.  It's been quite useful when we collaborate on the TOML code to have this testing code present and identical for both of us.

I'd argue that we should but in an issue for moving this into a unit test, but we also don't want that unit test blocking other valid PRs in the interim.  The feature flag makes it possible, but I feel it's complex enough that it should be its own PR and not added onto this one.

2022-05-05 11:40 UTC, IVlaD17 commented on src/main/io.cpp
> +        }
Created #1045 so I'll mark this as resolved.

2022-05-05 11:42 UTC, IVlaD17 commented on src/classes/atomtype.cpp
> +void AtomType::deserialize(toml::value node)
I've sorted that out but I also created #1046 to tackle `serialize()` methods added in #1008 because I wanted to keep this PR focused just on the PairPotentials.

2022-05-05 11:42 UTC, IVlaD17 commented on src/classes/atomtype.cpp
> +    if (!node["z"].is_uninitialized())
Changed it to that.

2022-05-16 14:02 UTC, merged