1227 Reference data G(r)
disorderedmaterials/dissolve pull request #1253
Opened 2022-10-10 14:51 UTC by trisyoungs

This PR addresses #1227, which is a bug caused by a previous PR removing the automatic generation of configuration contents on file load.  Thus, when any module read in from the file tries to Fourier transform associated reference data, the density value retrieved from the associated `Configuration` is zero, leading to divide-by-zero errors in the Fourier transform and subsequent death of any graphed values.

We solve this issue by returning `std::optional<double>` from the relevant density routines, allowing checks against the validity of the value to be made.

Closes #1227.

2022-10-28 09:26 UTC, rprospero requested changes
Just some error handling bits with the optional.  I like the setup, but we might as well take advantage of the information that the optional is giving us.

2022-10-28 09:26 UTC, rprospero commented on src/modules/epsr/process.cpp
> +    auto rho = *targetConfiguration_->atomicDensity();
I feel we should have a check here to return an error message if `rho` does not have a value.

2022-10-28 09:26 UTC, rprospero commented on src/modules/neutronsq/process.cpp
> +    auto rho = *rdfModule->effectiveDensity();
Again, we should return an error if rho is unset.

2022-10-28 09:26 UTC, rprospero commented on src/modules/rdf/functions.cpp
> +        double weight = ((cfgWeight / totalWeight) * *cfg->atomicDensity()) / rho0;
Error check

2022-10-28 09:26 UTC, rprospero commented on src/modules/rdf/functions.cpp
> +        return acc + pair.second / totalWeight / pair.first->atomicDensity().value();
Error check, but this is going to be a bit trickier, since it's inside the lambda.  My initial suggestion would be
```suggestion
        if (!acc) return {};
        auto density = pair.first->atomicDensity{};
        if (!density) return {};
        return *acc + pair.second / totalWeight / *density;
```

And then return an error message if the overall accumulate returns null.

2022-10-28 09:26 UTC, rprospero commented on src/procedure/nodes/add.cpp
> +                     *cfg->chemicalDensity());
Switch these to `value_or` so that we can handle a missing rho

2022-11-03 20:48 UTC, trisyoungs commented on src/gui/configurationtab_funcs.cpp
> +        ui_.DensityUnitsLabel->setText(rho ? QString::number(*rho) : "--");
Cool feature tho.

2022-11-03 21:02 UTC, trisyoungs commented on src/modules/rdf/functions.cpp
> +        return acc + pair.second / totalWeight / pair.first->atomicDensity().value();
Rather than "complicate" the `accumulate` call here, I've elected to perform a direct check in the preceding loop so that no lambda-based check is necessary.

2022-11-10 09:23 UTC, merged