1246 Use optional numeric controls where appropriate
disorderedmaterials/dissolve pull request #1319
Opened 2023-02-03 13:51 UTC by Danbr4d

Closes #1246 
The OptionalIntegerKeyword and OptionalDoubleKeywords can be used in more places:

 RDFModule, "Cutoff" keyword (eliminates "UseHalfCellWidth" bool)
 EPSRModule, potential limits
 MDModule, energy, output, and trajectory frequencies

2023-02-03 13:53 UTC, Danbr4d commented
Only thing I am unsure of is what textWhenNull to have and also what values to put in the trajectoryFrequency_ as it seems to be 0 everywhere I can see

2023-02-03 15:20 UTC, trisyoungs requested changes
Exactly the right idea, but we need to be careful when working with `std::optional`s since we can't assume the presence of a defined value, and need to cater for the `std::nullopt` case explicitly in places.

2023-02-03 15:20 UTC, trisyoungs commented on src/modules/md/md.cpp
> +    keywords_.add<OptionalIntegerKeyword>("Output", "EnergyFrequency",
Sorry - my merging in of #1308 means that your definitions here are in the old format! They should now be like:
```suggestion
    keywords_.add<OptionalIntegerKeyword>("EnergyFrequency",
```

2023-02-03 15:20 UTC, trisyoungs commented on src/modules/md/md.cpp
> +                                          "Frequency at which to calculate total system energy (or 0 to inhibit)",
I think we can now remove the "(or 0 to inhibit)" from the help text and the comments above the variables in the header.
```suggestion
                                          "Frequency at which to calculate total system energy",
```

2023-02-03 15:20 UTC, trisyoungs commented on src/modules/md/md.cpp
> +                                          0, std::nullopt, 5, "Inhibited");
For simplicity and consistency I would just go with "Off" for the special case here and in the others:
```suggestion
                                          0, std::nullopt, 5, "Off");
```

2023-02-03 15:20 UTC, trisyoungs commented on src/modules/md/md.h
>      // Frequency at which to calculate total system energy (or 0 to inhibit)
```suggestion
    // Frequency at which to calculate total system energy
```
etc.

2023-02-03 15:20 UTC, trisyoungs commented on src/modules/md/process.cpp
> +        Messenger::print("MD: Trajectory file will be appended every {} step(s).\n", trajectoryFrequency_.value());
Need to be careful here because the frequency can be undefined (i.e. `std::nullopt`) so it might be best to remove the `writeTraj` variable on line 23 and simply do:
```
if (trajectoryFrequency_.value_or(0) > 0)
```

2023-02-03 15:20 UTC, trisyoungs commented on src/modules/md/process.cpp
> +        Messenger::print("MD: Energy will be calculated every {} step(s).\n", energyFrequency_.value());
Same here.

2023-02-03 15:20 UTC, trisyoungs commented on src/modules/md/process.cpp
> +        Messenger::print("MD: Summary will be written every {} step(s).\n", outputFrequency_.value());
And here!

2023-02-03 15:20 UTC, trisyoungs commented on src/modules/md/process.cpp
> +        if ((step == 1) || (step % outputFrequency_.value() == 0))
And here, but you probably want to move the check for a valid value in `outputFrequency_` out of this `if` statement otherwise it's going to get a little messy.

2023-02-03 15:26 UTC, Danbr4d commented on src/modules/md/process.cpp
> +        Messenger::print("MD: Trajectory file will be appended every {} step(s).\n", trajectoryFrequency_.value());
I have these changes locally but I think they didn't get pushed up/got replaced in one of the other commits. Explains why its building locally but failing the tests

2023-02-03 17:25 UTC, Danbr4d commented
Made the changes you suggested but getting an error that I don't understand. Thought it was due to the frequency having 8 arguments but I changed that and still get the same error
![image](https://user-images.githubusercontent.com/115464393/216663487-56803175-0152-4463-8a37-82b7f4de72d2.png)

2023-02-08 09:04 UTC, trisyoungs requested changes

2023-02-08 09:04 UTC, trisyoungs commented on src/modules/md/md.cpp
> +    keywords_.add<OptionalIntegerKeyword>("Output", "EnergyFrequency", "Frequency at which to calculate total system energy",
Just the initial argument needs removing - this was the old way of specifying the group the keyword would be displayed in in the GUI, but this is now covered by the `setOrganisation()` method.
```suggestion
    keywords_.setOrganisation("Output");
    keywords_.add<OptionalIntegerKeyword>("EnergyFrequency", "Frequency at which to calculate total system energy",
```
etc.

2023-02-14 09:32 UTC, trisyoungs requested changes
Looking good.  Suggestions made for the default text values, and some corrections made to variable overwriting / logic in my old code (which your changes highlighted!).

2023-02-14 09:32 UTC, trisyoungs commented on src/modules/gr/process.cpp
>      if (useHalfCellRange_)
As discussed, the `useHalfCellRange_` variable and associated keyword can be removed since using a `std::optional<double>` for the `requestedRange_` variable covers this choice.

2023-02-14 09:32 UTC, trisyoungs commented on src/modules/md/md.cpp
> +                                          energyFrequency_, 0, std::nullopt, 10, "Off");
For consistency, let's make all the value steps `5`:
```suggestion
                                          energyFrequency_, 0, std::nullopt, 5, "Off");
```

2023-02-14 09:32 UTC, trisyoungs commented on src/modules/md/md.h
> +    std::optional<int> trajectoryFrequency_{0};
```suggestion
    std::optional<int> trajectoryFrequency_;
```

2023-02-14 09:32 UTC, trisyoungs commented on src/modules/md/process.cpp
> +        if ((step == 1) || (step % outputFrequency_.value_or(0) == 0))
I have a suspicion that this will write out every step (or maybe even crash!) if `outputFrequency_` is undefined, since the result of `step % 0` is undefined. It's safer to do:
```suggestion
        if (outputFrequency_ && (step == 1 || (step % outputFrequency_.value() == 0)))
```

2023-02-14 09:32 UTC, trisyoungs commented on src/modules/md/process.cpp
> +            if ((energyFrequency_.value_or(0) > 0) && (step % energyFrequency_.value_or(0) == 0))
And here:
```suggestion
            if (energyFrequency_ && (step % energyFrequency_.value() == 0))
```

2023-02-14 09:32 UTC, trisyoungs commented on src/modules/md/process.cpp
> +        if (trajectoryFrequency_.value_or(0) > 0 && (step % trajectoryFrequency_.value_or(0) == 0))
```suggestion
        if (trajectoryFrequency_ && (step % trajectoryFrequency_.value() == 0))
```

2023-02-14 09:32 UTC, trisyoungs commented on src/modules/md/process.cpp
> +                if ((energyFrequency_.value_or(0) > 0) && (step % energyFrequency_.value_or(0) == 0))
```suggestion
                if (energyFrequency_ && (step % energyFrequency_.value() == 0))
```

2023-02-15 14:23 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +    auto rminpt = rMinPT_ ? rMinPT_.value() : rmaxpt - 2.0;
Changing this bit also removed the setting of `nCoeffP_` optional which is now causing a crash. We need to do a similar thing as above, and change uses of `nCoeffP_.value()` to use our temporary var:
```suggestion
    auto rminpt = rMinPT_ ? rMinPT_.value() : rmaxpt - 2.0;
    auto ncoeffp = nCoeffP_ ? nCoeffP_.value() : std::min(int(10.0 * rmaxpt + 0.0001), mcoeff);
```

2023-02-16 11:41 UTC, trisyoungs approved these changes

2023-02-20 09:42 UTC, merged