initial set up of IntegerHistogram1D
disorderedmaterials/dissolve pull request #1431
Opened 2023-05-23 15:21 UTC by Danbr4d

Closes #1429. For simple counted statistical quantities (i.e. populations etc.) we require an analogous class to Histogram1D which handles integer binning and outliers properly.

2023-05-25 13:27 UTC, trisyoungs commented on src/math/integerhistogram1d.h
> +    std::vector<int> binCentres_;
All of these member variables can be deleted since we don't want / need them any more.

```suggestion
```

2023-05-25 13:27 UTC, trisyoungs commented on src/math/integerhistogram1d.h
> +    int maximum_;
I'm inclined to keep some sort of limits in since we might want to restrict against binning "silly" values. I would suggest that we change them to `std::optional`s to make sure their intent is clear, but keep the zero as the minimum limit since preventing negative numbers seems sensible (but perhaps not always desired!).  I've changed the comments too.
```suggestion
    // Minimum value allowed for binning
    std::optional<int> minimum_{0};
    // Maximum value allowed for binning
    std::optional<int> maximum_;
```

2023-05-25 13:27 UTC, trisyoungs commented on src/math/integerhistogram1d.h
> +    std::map<int, long int> histMap_;
As mentioned above, we need to tie together the "instantaneous" binned values and their running averages, which was previously managed by two `std::vector`s (`bins_` and `averages_`) of the same size. My suggestion would be to use a `std::pair`.  Also renamed it to be `bins_` since we can use it with the old one removed.
```suggestion
    // Map of histogram bin values to instantaneous counts and accumulated averages
    std::map<int, std::pair<long int, SampledDouble>> bins_;
```

2023-05-25 13:27 UTC, trisyoungs commented on src/math/integerhistogram1d.h
> +    bool insertIntoMap(int x);
Probably best to rewrite the `bin(double x)` to take an `int` rather than having a separate function for it.

2023-05-30 14:29 UTC, Danbr4d commented
Commented out some functions as they need editing to work with new parameters but will add them back in iteratively to check they work properly

2023-05-31 10:25 UTC, Danbr4d commented on src/math/integerhistogram1d.cpp
> +        averages_[value.first] += bins_[value.first].first;
Having issues with this operator as "more than one operand matches it in SampledDouble"

2023-05-31 10:26 UTC, Danbr4d commented on src/math/integerhistogram1d.cpp
> +    if (!parser.writeLineF("{} {} {}\n", minimum_, maximum_, 1))
I think the optinalInt for maximum_ and minimum_ are causing problems here as well

2023-05-31 19:45 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    if (!parser.writeLineF("{} {} {}\n", minimum_, maximum_, 1))
We'll need to write the information out a bit differently, I think, since both limits are optional.  I'd suggest something like this:
```suggestion
    if (!parser.writeLineF("{} {} {} {}\n", Dissolve::btoa(minimum_), minimum_.value_or(0), Dissolve::btoa(maximum_), maximum_.value_or(0)))
```

This would write out a line like this (for the default values of `minimum_ = 0` and `maximum_` as undefined:
```
True  0  False  0
```

2023-05-31 19:45 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    }
Couple of things here.  First, the independent `averages_` vector is no longer needed, since we're tying the average value to the bin.  Second, the pair should be `int, SampledDouble` rather than a vector for the latter.  Third, you should be able to simplify the code here by using the `std::map` feature that returns a new value if the accessed key isn't currently present:
```suggestion
bins_[x].first++;
```
Glorious, huh? :smile:

Also need to do the check on min/max limits here before we do the binning.

2023-05-31 19:45 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +        averages_[value.first] += bins_[value.first].first;
Hmmm.  Not sure why that's happening, but once `averages_` is removed the loop would look something like this (I think!):
```suggestion
        value.second += value.first;
```
Basically, just summing in the current counts (first) to the associated average (second)

2023-06-06 09:46 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +void IntegerHistogram1D::initialise(int xMin, int xMax, int binWidth)
This function needs a bit of modifiication - it doesn't need the `binWidth` argument any more, and the min/max arguments should be `std::optional<int>`s.

2023-06-06 09:46 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +}
This function I think is redundant now - we don't currently use it, and the function it performs needs to be essentially rewritten in `updateAccumulatedData()`.

2023-06-06 09:46 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    }
This is where things aren't as straightforward as for the well-defined, Histogram1D case. In the worst case we have no idea what the limits of the data are, and so need to work them out from the data contained in the  `std::map` `bins_`. Once the limits are established the `Data1D` object (`accumulatedData_`) can be initialised to the correct size, and then the `SampledDouble` values contained in `bins_` "re-binned" into the `Data1D`.  Hopefully this makes sense!  If you look at the unit test I just added you'll see the first part of this (the limit determination) written out already which you can steal.

2023-06-06 09:46 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    maximum_ = 0;
Need to be careful here, since this will reset the limits to an unusable range. 
```suggestion
    minimum_ = 0;
    maximum_ = std::nullopt;
```

2023-06-07 09:41 UTC, Danbr4d commented on src/math/integerhistogram1d.cpp
> +}
I've noticed that this function is meant to be used in the `initialise` but isn't, do I add it back in there and keep the `setUpAxis()` function or should I still move it to `updateaccumulatedData()`?

2023-06-07 11:18 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +}
As written this is only useful for static axes with defined min/max, but our histogram is never guaranteed to have unchanging min/max bin values.  You've already been accounting for that with the expectedMinimum and maximum stuff, so I would just bin this code entirely.

2023-06-14 14:10 UTC, trisyoungs reviewed
I've fixed up a few things here - see if all the commits make sense!  Have extended the unit test and now they all pass.

Made some comments on the final remaining pieces of work (mostly boring I/O stuff, but necessary!).

2023-06-14 14:10 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +}
I'd have to check where exactly this gets used in the code, but as-written the function copies `accumulatedData_` (which may not yet exist...) and then _appends_ values to the back of the array, rather than setting them.  The actual function here would be quite similar to the `updateAccumulatedData()`, so we should probably consider taking the guts of that function out into a separate private function `const Data1D::createtDisplayData()` which does all the min/max determination and sets up the x-axis with the bin values.  Then the `data()` and `updateAccumulatedData()` functions can call that and just set the value/error data differently.

2023-06-14 14:10 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +// }
Let's delete these fully for now - no point in worrying about writing them until we need them.

2023-06-14 14:10 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +        return false;
The `serialise` function needs to write out the `bins_` data.  It will need to write out the number of keys in the `bins_` map on the next line, followed by the key, count, and SampledDouble data for each bin in the map (one set of bin data per line).

2023-06-14 14:10 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    initialise(parser.argd(0), parser.argd(1));
This needs adjusting to reflect format of the limits written in the `serialise()` function.

2023-06-20 10:50 UTC, trisyoungs requested changes
Pretty much all good - one minor issue and a few picky corrections to make, then I think you can re-request a review from @rprospero.

2023-06-20 10:50 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    Data1D data;
Just for "data locality" I would delete this from here and move it further down to where it is first used.
```suggestion
```

2023-06-20 10:50 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    for (auto n = 0; n < expectedNBins; n++)
Being super-picky, but a prefix increment (`++n`) requires less CPU operations than a postfix increment (`n++`), and either could be used here.
```suggestion
    for (auto n = 0; n < expectedNBins; ++n)
```

2023-06-20 10:50 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +
Just moving the blank line.
```suggestion

    for (auto &[key, value] : bins_)
```

2023-06-20 10:50 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    for (int n; n <= nBins; n++)
Your start value is undefined here which is a bit dangerous! Loop starts at zero so can use the condition `n < nBins`. Plus `auto` and the prefix `++`.
```suggestion
    for (auto n = 0; n < nBins; ++n)
```

2023-06-20 10:50 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +        bins_[parser.argli(0)].second.deserialise(parser);
Yes, that's the way to do it!  I'd make a small correction just to be on the safe side as well as avoiding doing the string-to-int conversion twice:
```suggestion
        auto bin = parser.argi(0);
        bins_[bin].first = parser.argli(1);
        bins_[bin].second.deserialise(parser);
```

2023-06-20 13:35 UTC, rprospero reviewed
I've got a few questions below on bits that I didn't quite understand, along with some suggestions.

2023-06-20 13:35 UTC, rprospero commented on src/math/integerhistogram1d.h
> +    long int nBinned_;
I might have missed something, but is `nBinned_` ever not zero?  It doesn't seem to get updated when new elements are added to the histogram?  I'm not quite sure that I'm understanding properly, but the comment makes it sound like a copy of `bins_.size()`

2023-06-20 13:35 UTC, rprospero commented on src/math/integerhistogram1d.cpp
> +    }
Is this a significant restriction?  We're using maps, not arrays, so we can add them and get a union of the data.  Conversely, two histograms might have the same number of bins, but different bin values, and this function will only update the bins that are in the `this` array, ignoring any bins that it didn't have.

2023-06-20 14:05 UTC, trisyoungs commented on src/math/mathfunc.cpp
> +
My concern with that was that you still have to cast to an `int`, and if the result of `std::lround` is, for example, `2.999999999997` then we'll convert potentially down to `int` `2`.  However, just saw that a function `std::lrint` exists and which we should use instead of implementing our own `nInt` function.

2023-06-20 14:07 UTC, trisyoungs commented on src/math/integerhistogram1d.h
> +    long int nBinned_;
Good catch - there should be a `++nBinned_` after `bins_[x].first++;` on line 116.

2023-06-20 14:08 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +        bins_[value.first].first += other.bins_[value.first].first * factor;
Another good catch!  And fair comment on the unit test - I'll add one once the other changes are made.

2023-06-20 14:11 UTC, trisyoungs commented on src/math/integerhistogram1d.h
> +    std::map<int, std::pair<long int, SampledDouble>> bins_;
That would be more in line with the implementations in `Histogram1D` etc., but here we elected to go with the `std::pair` to tie the counts and averages together, mostly to ensure parity between the two quantities.

2023-06-20 14:11 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    }
This is just old code that hasn't been updated yet - we'll add it to the To-Do!

2023-06-20 14:39 UTC, Danbr4d commented on src/math/integerhistogram1d.cpp
> +    }
So is a check needed instead to see if the same bin values are present before adding them and if not it needs to add in the missing ones too?

2023-06-22 19:58 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    std::pair<Data1D, std::optional<int>> average = createDisplayData();
For cleanliness this can be `auto`:
```suggestion
    auto average = createDisplayData();
```

2023-06-22 19:58 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +const std::pair<Data1D, std::optional<int>> IntegerHistogram1D::createDisplayData()
We explicitly test for the optional limits and set them to zero (or the other limit if only one bin exists) so this function can return just `std::pair<Data1D, int>`.

2023-06-22 19:58 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    averages_.clear();
Can delete these since it's done in `clear()`.
```suggestion

```

2023-06-22 19:58 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    averages_.clear();
Don't want to clear the averages here - they're long lived over many accumulations - so just the bin counts.
```suggestion
```

2023-06-22 19:58 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +        averages_[key] += (SampledDouble)raw_[key];
Small thing, but we can convert to `double` here instead of `SampledDouble` to keep things simple.
```suggestion
        averages_[key] += (double)raw_[key];
```

2023-06-22 19:58 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +        result.values()[(key)] = value;
Few unnecessary brackets.
```suggestion
        result.values()[key] = value;
```

2023-06-22 19:58 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    return true;
We don't cover this (de)serialise yet with a system test - we will when the Histogram module comes along - but this definitely wouldn't have been happy!
```suggestion
    for (auto n = 0; n < nBins; ++n)
    {
        if (parser.getArgsDelim(LineParser::Defaults) != LineParser::Success)
            return false;

        auto bin = parser.argi(0);
        raw_[bin] = parser.argli(1);
        averages_[bin].deserialise(parser);
    }
    
    return true;
```

2023-06-22 19:58 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +    }
Need to write the bin counts and averages as pairs, per bin:
```suggestion
    {
        if (!parser.writeLineF("{} {} \n", key, value))
            return false;
        if (!averages_[key].serialise(parser))
            return false;
    }
```

2023-06-22 19:58 UTC, trisyoungs commented on src/math/integerhistogram1d.h
> +    const std::pair<Data1D, std::optional<int>> createDisplayData();
Just need a comment for the function
```suggestion
    // Create display data object covering extents of current bins
    const std::pair<Data1D, std::optional<int>> createDisplayData();
```

2023-06-22 19:58 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +// Create dsiplay data
Bit more detail:
```suggestion
// Create display data object covering extents of current bins
```

2023-06-23 13:41 UTC, Danbr4d commented on src/math/integerhistogram1d.cpp
> +const std::pair<Data1D, std::optional<int>> IntegerHistogram1D::createDisplayData()
So then will the return for the function `return expectedMinimum.value()`?

2023-06-23 22:25 UTC, trisyoungs commented on src/math/integerhistogram1d.cpp
> +const std::pair<Data1D, std::optional<int>> IntegerHistogram1D::createDisplayData()
Yep, exactly that.

2023-06-26 11:30 UTC, rprospero approved these changes

2023-06-27 08:35 UTC, trisyoungs approved these changes

2023-06-27 08:36 UTC, merged