Species charge handling - Part 1
disorderedmaterials/dissolve pull request #1450
Opened 2023-06-12 10:02 UTC by jws-1

Initial PR regarding species charge handling (#1449).
Added the following menu items to the Species menu:
- Reduce Sig. Figs. in Charges - this is the first step towards smoothing charges (#1448), but additionally we need to add the option to scale and sum charges to 0/-1/+1.
- Copy Atom Charges from Atom Types - copies the charges from the defined Atom Types to the current species. Closes #1446.
- Set Atom Type Charges From Species - averages the charges over the atom types in the current species whilst offering the option to "test" by outputting the proposed changes to Messages, along with their standard deviations. Closes #1447.

2023-06-12 11:12 UTC, trisyoungs requested changes
A few algorithmic comments, but otherwise very nice indeed.

2023-06-12 11:12 UTC, trisyoungs commented on src/gui/menu_species.cpp
> +                   "This cannot be undone! Proceed?");
```suggestion
    msgBox.setWindowTitle("Set Atom Type Charges from Species Atoms");
    msgBox.setText("This will replace the current atom type charges "
                   "with the average charge of relevant species atoms.\n\n"
                   "This cannot be undone! Proceed?");
```

2023-06-12 11:12 UTC, trisyoungs commented on src/gui/menu_species.cpp
> +    }
I think you can just simplify this to:
```suggestion
    for (auto &atom : species->atoms())
        charges[atom.atomType()] += atom.charge();
```

2023-06-12 11:12 UTC, trisyoungs commented on src/gui/menu_species.cpp
> +}
Here, I would exit immediately if `No`, then always print out the charge map, then change the actual charges if `Yes`.

2023-06-12 11:12 UTC, trisyoungs commented on src/gui/menu_species.cpp
> +            Messenger::print("{}: {} -> {} \u00b1 {}", atomType->name(), atomType->charge(), charges[atomType].value(),
May also be nice to include the number of data contributing to each average, just to give full information to the user.

2023-06-12 11:12 UTC, trisyoungs commented on src/gui/menu_species.cpp
> +                             "Enter the number of significant figures to use for all atoms", 1, 1, 100, 1, &ok);
A nicer default:
```suggestion
                             "Enter the number of significant figures to use for all atoms", 3, 1, 100, 1, &ok);
```

2023-06-12 11:12 UTC, trisyoungs commented on src/gui/menu_species.cpp
> +}
The temporary variable is a bit redundant:
```suggestion
    for (auto &atom : species->atoms())
        atom.setCharge(std::round(atom.charge() * std::pow(10, significantFigures)) / std::pow(10, significantFigures));
```

2023-06-12 11:12 UTC, trisyoungs commented on src/gui/menu_species.cpp
> +            Messenger::print("{}: {} -> {} \u00b1 {}", atomType->name(), atomType->charge(), charges[atomType].value(),
Would be nice also to have a header line before the charge map gets printed, just to clarify what it is that we're seeing!

2023-06-12 12:40 UTC, jws-1 commented on src/gui/menu_species.cpp
> +    }
Yes, much cleaner!

2023-06-13 07:41 UTC, trisyoungs requested changes

2023-06-13 07:41 UTC, trisyoungs commented on src/gui/menu_species.cpp
> +        }
Just spotted this one.  Here's another double loop that can be reduced right back to a single one since there's no need to look up the atom type, we can just use it (*if* the atom has one set):
```suggestion
        for (auto &atom : species->atoms())
            if (atom.atomType())
                atom.setCharge(atomType->charge());
```

2023-06-13 07:41 UTC, trisyoungs commented on src/gui/menu_species.cpp
> +    fullUpdate();
This function is fundamentally the same as the existing one above, save for a slightly different scale factor.  In order not to confuse the user with two very similar (menu) functions perhaps we should consider combining the two into the one dialog with "Scale", "Scale To", and "Cancel" buttons?

2023-06-14 08:27 UTC, trisyoungs approved these changes
One small correction to make, then I think we should get this merged in.  Having just used the new features in earnest there are some obvious other things to do which are closely related, so I'll update the epic.

2023-06-14 08:27 UTC, trisyoungs commented on src/gui/gui.ui
> +    <string> Set Atom Type C&amp;harges from Species...</string>
These menu items have the same shortcut!

2023-06-14 08:51 UTC, jws-1 commented on src/gui/gui.ui
> +    <string> Set Atom Type C&amp;harges from Species...</string>
Oops! Sorted.

2023-06-14 11:36 UTC, merged