Fragment Rotation (fragments part 4)
disorderedmaterials/dissolve pull request #1478
Opened 2023-06-28 15:56 UTC by jws-1

Following on from previous work regarding fragments, this PR implements the ability to rotate fragments (or any collection of atoms that compose a site) by a scalar value or an expression. This can be done using a `RotateProcedureNode`. Additionally, a couple of unit tests are included for rotation and fragment site generation.

2023-06-29 10:36 UTC, trisyoungs requested changes
Lots to like here. :+1: Have made some file / class naming requests (again!) so apologies in advance for that.  Query on the maths behind the process as well.

2023-06-29 10:36 UTC, trisyoungs commented on src/classes/site.cpp
>  Site::~Site() = default;
While we're modifying these files, can we remove this and do it in the header instead for neatness?
```suggestion
```

2023-06-29 10:36 UTC, trisyoungs commented on src/classes/site.h
> +    int uniqueSiteIndex_;
An `optional` would perhaps be a better choice, and remove the need for the magic number `-1`?
```suggestion
    std::optional<int> uniqueSiteIndex_;
```

2023-06-29 10:36 UTC, trisyoungs commented on src/procedure/nodes/CMakeLists.txt
> +  rotate.cpp
More naming shenanigans I'm afraid!  Since this will operate specifically on fragments I think it should be named as such - `rotatefragment.cpp`.  There is every chance that a node to rotate molecules will be introduced at some point, and this will take the name `rotate.cpp`.

2023-06-29 10:36 UTC, trisyoungs commented on src/procedure/nodes/node.cpp
> +                     {ProcedureNode::NodeType::Rotate, "Rotate"},
```suggestion
                     {ProcedureNode::NodeType::RotateFragment, "RotateFragment"},
```

2023-06-29 10:36 UTC, trisyoungs commented on src/procedure/nodes/rotate.cpp
> +RotateProcedureNode::RotateProcedureNode(std::shared_ptr<SelectProcedureNode> site)
```suggestion

RotateProcedureNode::RotateProcedureNode(std::shared_ptr<SelectProcedureNode> site)
```

2023-06-29 10:36 UTC, trisyoungs commented on src/procedure/nodes/rotate.h
> +class RotateProcedureNode : public ProcedureNode
```suggestion

class RotateProcedureNode : public ProcedureNode
```

2023-06-29 10:36 UTC, trisyoungs commented on src/procedure/nodes/rotate.h
> +    NodeValue rotation_;
Maybe set a default here?
```suggestion
    NodeValue rotation_{90.0};
```

2023-06-29 10:36 UTC, trisyoungs commented on src/procedure/nodes/select.cpp
> +    : ProcedureNode(ProcedureNode::NodeType::Select, {ProcedureNode::AnalysisContext, ProcedureNode::GenerationContext}),
:+1:

I knew this would come in useful!

2023-06-29 10:36 UTC, trisyoungs commented on unit/procedure/CMakeLists.txt
> +dissolve_unit_test(rotate.cpp)
Don't forget the naming here.

2023-06-29 10:36 UTC, trisyoungs commented on src/procedure/nodes/registry.cpp
> +    // Sites
Man, I am _fussy_ when it comes to blank lines.... :smiley:
```suggestion

    // Sites
```

2023-06-29 10:36 UTC, trisyoungs commented on src/procedure/nodes/rotate.cpp
> +    }
This will rotate the fragment about the cardinal X, Y, or Z axes, whereas what you want to do is rotate about the local (site) X, Y, or Z axes, so you'll need to multiply this matrix by the site axes matrix.

2023-06-29 10:36 UTC, trisyoungs commented on unit/procedure/rotate.cpp
> +    }
Isn't this identical to the test above?  A nicer one would be to rotate once about an axis by 90 degrees and check that everything is still in a (different) plane.

2023-06-29 13:18 UTC, jws-1 commented on src/procedure/nodes/rotate.cpp
> +    }
Funnily enough, that's what I had done in the beginning...!

2023-06-30 20:05 UTC, trisyoungs reviewed
Couple of minor things spotted - looks like a dodgy merge.

2023-06-30 20:05 UTC, trisyoungs commented on src/classes/speciessite.cpp
> +                                        acc.second + mass);
It might be that C++17 won't let this happen, but can we do this instead?
```suggestion
                                    return {acc.first + parent_->box()->minimumImage(parent_->atom(idx).r(), ref) * mass,
                                        acc.second + mass};
```

2023-06-30 20:05 UTC, trisyoungs commented on src/classes/speciessite.cpp
> +
```suggestion
```

2023-06-30 20:05 UTC, trisyoungs commented on src/classes/speciessite.h
> +#include "classes/box.h"
Should this not have been included in the cpp rather than the header? We don't cite the `Box` class here...

2023-06-30 20:05 UTC, trisyoungs commented on src/neta/neta.cpp
> +    identifiers_.clear();
There it is!

2023-06-30 20:05 UTC, trisyoungs commented on src/procedure/nodes/node.cpp
> +                     {ProcedureNode::NodeType::RestraintPotential, "RestraintPotential"},
Any reason why the restraint-related stuff is coming in to this PR?

2023-06-30 20:23 UTC, jws-1 commented on src/classes/speciessite.cpp
> +#include "classes/molecule.h"
Probably happened automatically!

2023-06-30 20:30 UTC, jws-1 commented on src/procedure/nodes/node.cpp
> +                     {ProcedureNode::NodeType::RestraintPotential, "RestraintPotential"},
The merge wanted to break the alphabetical ordering in some places (`RotateFragment` vs `RestraintPotential`), which made things a bit annoying...

2023-06-30 20:41 UTC, trisyoungs commented on src/procedure/nodes/node.cpp
> +                     {ProcedureNode::NodeType::RestraintPotential, "RestraintPotential"},
Ah yes, I should have realised that!  Shouldn't review PRs whilst half-focussing on GoW: Ragnarok...

2023-06-30 20:58 UTC, jws-1 commented on src/classes/speciessite.h
> +#include "classes/box.h"
Sloppy!

2023-06-30 22:23 UTC, trisyoungs commented
Bad suggestion on the type deduction.  Curse that C++17!

2023-06-30 22:28 UTC, jws-1 commented on src/procedure/nodes/node.cpp
> +                     {ProcedureNode::NodeType::RestraintPotential, "RestraintPotential"},
That actually sounds like a good way to review PRs!

2023-06-30 22:30 UTC, trisyoungs commented on src/procedure/nodes/node.cpp
> +                     {ProcedureNode::NodeType::RestraintPotential, "RestraintPotential"},
"Boy! Follow your path, but you must not lose focus!!"

2023-07-01 14:31 UTC, trisyoungs commented
Took another look at the applied to the MOF and fixed a couple of issues - still one big one remains (this is the configuration with a 45degree rotation about X applied):
![image](https://github.com/disorderedmaterials/dissolve/assets/11457350/de80c453-24a6-44e2-9b4c-d9d17f03ee67)
If you look at the illustration of the species sites on the sites tab it does look like the axes arrows are pointing in the correct direction but the rotated site "box"es aren't in the same orientation...

2023-07-03 08:14 UTC, jws-1 commented
> Took another look at the applied to the MOF and fixed a couple of issues - still one big one remains (this is the configuration with a 45degree rotation about X applied): ![image](https://user-images.githubusercontent.com/11457350/250285447-de80c453-24a6-44e2-9b4c-d9d17f03ee67.png) If you look at the illustration of the species sites on the sites tab it does look like the axes arrows are pointing in the correct direction but the rotated site "box"es aren't in the same orientation...

For some reason I can't see the image you've uploaded. However, shouldn't the species sites shown on the sites tab remain unaltered during this process?

2023-07-03 10:23 UTC, trisyoungs commented
Another try for a picture!
![image](https://github.com/disorderedmaterials/dissolve/assets/11457350/3906f5eb-e5a9-4fa3-a0a2-68262344fd03)
The species sites don't get modified during the process, but they don't look entirely correct to begin with for some reason...

2023-07-03 13:58 UTC, trisyoungs approved these changes
One critical change to add, then this is all good to go! :+1:

You should try the example file out with 45.0 rotation about X and watch everything neatly snap into line...

2023-07-03 13:58 UTC, trisyoungs commented on src/procedure/nodes/rotatefragment.cpp
> +    rotationMatrix *= site->axes();
Don't need this multiplication. Our rotation matrix is now about one of the defined axes of the site, so no further matrix manipulation required.
```suggestion
```

2023-07-03 14:07 UTC, merged