Remove nodes
disorderedmaterials/dissolve pull request #1485
Opened 2023-07-04 11:09 UTC by jws-1

This PR adds the ability to remove nodes from a procedure. Closes #1420.

2023-07-04 12:52 UTC, trisyoungs requested changes
Good start, but it's time to revisit (and re-despise) Qt's Model-View framework I'm afraid!

2023-07-04 12:52 UTC, trisyoungs commented on src/gui/procedureWidgetFuncs.cpp
> +        updateNodeTree();
Ah, you see what you've done here is opened up a nasty can of worms for yourself! Unfortunately it's bad practice to remove the node from the procedure directly like this, since our widget is guided by a model (`ProcedureModel` in `src/gui/models/procedureModel.cpp` - already loving the new naming scheme!). That means that to ensure correctness we need to delete the node via the model itself so it understands what has changed. This would also emit `dataChanged` so that other keywords in the procedure are updated following (potentially) the removal of a node that one or more of them referenced.

2023-07-04 12:52 UTC, trisyoungs commented on src/gui/procedureWidgetFuncs.cpp
> +    }
As a related issue, once a node has been deleted the controls are still displayed for it, and no node ends up being selected in the tree.

2023-07-04 13:38 UTC, jws-1 commented on src/gui/procedureWidgetFuncs.cpp
> +        updateNodeTree();
Of course.. Luckily I have plenty of experience with models!

2023-07-05 12:28 UTC, trisyoungs commented on src/gui/models/procedureModel.cpp
> +#include "qabstractitemmodel.h"
Not sure why this `#include` is here?  I don't need it on my system, and it's also a system header being included in quotes rather than `<>`. VS to blame?

2023-07-05 12:28 UTC, trisyoungs commented on src/gui/procedureWidget.h
> +    void on_DeleteNodeButton_clicked(bool checked);
Bug :lady_beetle: report!  If I click the delete node button when the list is empty (or presumably when no node is selected) I get a segfault.  May be nicer UX to disable the button if no node is selected.

2023-07-05 12:28 UTC, trisyoungs commented on src/gui/models/procedureModel.cpp
> +
Need to emit `dataChanged` otherwise we don't properly update other things.
```suggestion

    emit(dataChanged(QModelIndex(), QModelIndex());
```

Furthermore, need to call `updateControls()` in `ProcedureWidget::procedureDataChanged()` (line 134) since the relationships between data are validated by the function, but the incorrect values are still displayed in the current control widget because we don't update it.

2023-07-05 12:56 UTC, jws-1 commented on src/gui/models/procedureModel.cpp
> +#include "qabstractitemmodel.h"
That'd be my neovim LSP config to blame!

2023-07-05 13:39 UTC, trisyoungs commented on src/gui/models/procedureModel.cpp
> +#include "qabstractitemmodel.h"
Why am I only just hearing about `neovim`? :disappointed:

2023-07-07 08:08 UTC, trisyoungs approved these changes
Looks good, works nicely!  I'm obliged to mention for the general record that the inability to undo a node deletion (or addition, or move, or keyword change...) is a bit of an issue. So, while we are not using TOML for input file I/O immediately, it is in our interest to get that up to scratch and compiled as part of the `develop` stream so we can leverage it for undo/redo actions like this.

Aaaaaanyway, that's obviously not in scope for this PR, but I just wanted to write it down!

2023-07-07 08:13 UTC, jws-1 commented
> Looks good, works nicely! I'm obliged to mention for the general record that the inability to undo a node deletion (or addition, or move, or keyword change...) is a bit of an issue. So, while we are not using TOML for input file I/O immediately, it is in our interest to get that up to scratch and compiled as part of the `develop` stream so we can leverage it for undo/redo actions like this.
> 
> Aaaaaanyway, that's obviously not in scope for this PR, but I just wanted to write it down!

Yes, I thought it might be an issue. I was tempted to include a dialog to validate the user's decision - but I decided it might be a bit annoying!

2023-07-07 08:14 UTC, merged