Node-ify Temperature
disorderedmaterials/dissolve pull request #1492
Opened 2023-07-05 16:03 UTC by jws-1

This PR moves the Temperature for configurations from being a GUI control to a node: `Temperature`. Closes #146.

2023-07-06 09:08 UTC, trisyoungs requested changes
Looks good, but I think there's a bit more useful work we should do so as not to unnecessarily confuse our users!

First, from the main menu when a user creates a new `Configuration` we need to add our new `TemperatureNode` at the top of the procedure - see `gui/addConfigurationDialogFuncs.cpp`. It should go in at around line 183.

Second, I think we should add a new menu item to allow the temperature of an existing configuration to be set. We shouldn't force the user to regenerate the config from the beginning if they need to tweak the temperature!

2023-07-06 09:08 UTC, trisyoungs commented on src/main/keywords_configuration.cpp
> +                Messenger::warn("The TemperatureKeyword will be deprecated in future versions.\n");
```suggestion
                Messenger::warn("The 'Temperature' keyword will be deprecated in a future version.\n");
```

2023-07-06 09:08 UTC, trisyoungs commented on src/procedure/nodes/temperature.cpp
> +    keywords_.add<NodeValueKeyword>("Temperature", "Temperature in K", temperature_, this);
```suggestion
    keywords_.add<NodeValueKeyword>("Temperature", "Temperature (K)", temperature_, this);
```

2023-07-06 09:08 UTC, trisyoungs commented on src/procedure/nodes/temperature.cpp
> +bool TemperatureProcedureNode::mustBeNamed() const { return false; }
```suggestion

bool TemperatureProcedureNode::mustBeNamed() const { return false; }
```

2023-07-06 09:08 UTC, trisyoungs commented on src/procedure/nodes/temperature.cpp
> +// Execute node
```suggestion

// Execute node
```

2023-07-06 15:44 UTC, trisyoungs approved these changes
Again, just minor stuff. :+1:

We now don't display the temperature on the `ConfigurationTab`, but as long as we're anticipating the tab redesign to be done in the near future no problem.  If not, then adding a label in during the interim is the way to go.

2023-07-06 15:44 UTC, trisyoungs commented on src/gui/addConfigurationDialogFuncs.cpp
> +    generator.createRootNode<TemperatureProcedureNode>("Temperature");
I'd just default this one so it gets the standard node naming
```suggestion
    generator.createRootNode<TemperatureProcedureNode>({});
```

2023-07-06 15:44 UTC, trisyoungs commented on src/gui/gui.ui
> +    <string>Adjust Temperature...</string>
```suggestion
    <string>Adjust &amp;Temperature...</string>
```

2023-07-06 15:44 UTC, trisyoungs commented on src/gui/menu_configuration.cpp
> +                                               -10000.0, 10000.0, 3, &ok);
Well, that's breaking the laws of physics!  :smiley:
```suggestion
                                               0.0, 1000000.0, 3, &ok);
```

2023-07-06 15:44 UTC, trisyoungs commented on src/procedure/nodes/temperature.cpp
> +TemperatureProcedureNode::TemperatureProcedureNode()
All hail the BLP!
```suggestion

TemperatureProcedureNode::TemperatureProcedureNode()
```

2023-07-06 15:44 UTC, trisyoungs commented on src/procedure/nodes/temperature.cpp
> +bool TemperatureProcedureNode::mustBeNamed() const { return false; }
Convention.
```suggestion
// Return whether a name for the node must be provided
bool TemperatureProcedureNode::mustBeNamed() const { return false; }
```

2023-07-06 15:44 UTC, trisyoungs commented on src/procedure/nodes/temperature.h
> +class TemperatureProcedureNode : public ProcedureNode
```suggestion

class TemperatureProcedureNode : public ProcedureNode
```

2023-07-06 15:58 UTC, jws-1 commented on src/gui/menu_configuration.cpp
> +                                               -10000.0, 10000.0, 3, &ok);
Just keeping you on your toes!

2023-07-07 08:09 UTC, trisyoungs commented
Agreed.  We'll leave this as-is for now, and work the GUI reorganisation to address the issue.

2023-07-07 08:09 UTC, trisyoungs approved these changes

2023-07-07 08:14 UTC, merged