Reorganise GUI
disorderedmaterials/dissolve pull request #1500
Opened 2023-07-06 14:24 UTC by jws-1

This is currently a draft PR, to get feedback from a UI/UX perspective.

Shouldn't be merged in until #1490, #1491 and #1492 have been merged in.

2023-07-06 21:32 UTC, trisyoungs reviewed
OK, for the `SpeciesTab` I think the toolbox is a good solution, if a touch on the ugly side (not your fault!).  For the `ConfigurationTab` its nice and clean, but I'm going to vote against the actual `QStatusBar` for two reasons. First, I always disliked having to programmatically create all the content in them, rather than doing it with the UI. Second, I don't think it has the control we need or want. Actually, the third one not necessarily related to the `QStatusBar` is the little form that pops up when you hover over the box icon - on my laptop (Wayland) you have to click on it to get rid of it!

I've mocked up what I have in my head using sunken `QFrames` and disabled `QToolButton`s as the icon holders.  The box lengths angles can easily be encapsulated in  a simple `QToolTip` for the label. The density units should be a combo box, but you get the idea. The final two numbers are the number of molecules and number of atoms.

![image](https://github.com/disorderedmaterials/dissolve/assets/11457350/6b1e0d4f-a062-4e65-9283-8683c26d07b2)

2023-07-06 21:54 UTC, jws-1 commented
> 

Well.. that's definitely much better looking than what I had in mind!

2023-07-07 21:03 UTC, trisyoungs reviewed
First batch of comments, but this is all heading in the right direction.  I had a thought about the organisation of the `SpeciesTab`, trying to remove the horrid `QToolBox` and make it a bit more consistent with the `ConfigurationTab`:
![image](https://github.com/disorderedmaterials/dissolve/assets/11457350/c34e780b-8027-4b75-9c58-cc879f3bf04e)

Here we're using the same ideas for the top information bar as in the `ConfigurationTab`, meaning that we can remove the "Box" toolbox on the left, and I've ditched the `QToolBox` entirely for an arrangement of buttons and frames which can be hidden as the buttons are selected.  Just a thought!

2023-07-10 09:55 UTC, trisyoungs requested changes
Round 2!  This is working really well, I think, and the new speciestab layout feels pretty natural to use. I haven't fully played around with all the context menu options, but the ones I did try worked just as I expected them to which was nice!

Gonna need some new icons at some point.

Have made some more suggestions for improvements in the comments, but :+1: :+1:

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/configurationTab.h
> +    // Allow editing of the generator
These updated comments might be accurate, but the functions to prevent/allow editing are still general across all widget types, so I would stick to "within tab".

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/configurationTabFuncs.cpp
> +    boxInfo += QString("<b>%1:</b>  %2").arg(QString::fromUtf8("\u03B3")).arg(box->axisAngles().z);
Gotta have some units! Angstroms for the lengths (&#8491;) and degrees for the angles. Space between number and Angstrom, and none between number and degrees, otherwise I'll get grumpy. :)

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/geometryDialog.ui
The font in the dialog is the default size (12 pt) while we reduce that for Dissolve.  It's annoying that widgets, especially dialogs and `QMenu`s, don't seem to inherit their parent's font, so you'll have to grab it and set it manually when you create it.

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/geometryDialogFuncs.cpp
> +
```suggestion
```

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/speciesTab.h
> +    void buttonGroupToggled(QAbstractButton *button, bool checked);
Strictly speaking this should be a `private slot`.

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/speciesTab.ui
I actually think this layout works really well.  One issue I had with it was that the buttons and frame contents seemed to blend into one continuous mess, so I made a couple of small tweaks to get the result in the pic below:

- Boldified the button titles
- Placed each button / frame pair in its own `QWidget` container with zero margins and zero spacing
- Reduced the spacing in the overall vertical container from `6` to `4` in line with the rest of Dissolve.

![image](https://github.com/disorderedmaterials/dissolve/assets/11457350/c713bc91-382b-467b-a5f0-37e27646dbd5)

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/speciesTabFuncs.cpp
> +    boxInfo += QString("<b>%1:</b>  %2").arg(QString::fromUtf8("\u03B3")).arg(box->axisAngles().z);
Units.

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/speciesViewer_input.cpp
> +            species_->addSite(joinStrings(species_->selectedAtoms(), " ", [](const auto &i) { return i->atomType()->name(); }));
Prefer underscores to spaces for generated names in Dissolve.
```suggestion
            species_->addSite(joinStrings(species_->selectedAtoms(), "_", [](const auto &i) { return i->atomType()->name(); }));
```

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/configurationTab.ui
For consistency  we should adopt the same left-hand "custom tab" stack for the `ConfigurationTab` , even though its just the Generator and that might get moved at some point.

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/configurationTabFuncs.cpp
> +    ui_.MoleculePopulationLabel->setText(QString::number(configuration_->nMolecules()));
I think a static tooltip on these two frames explicitly stating "Number of molecules in the configuration" and "Number of atoms in the configuration" would be useful.

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/speciesTab.ui
Also, no reason why we shouldn't have a "Number of atoms in the species" frame on our little status bar.  Also, actually, one displaying the empirical formula (as is done currently in the bottom of the viewer) would be nice. I _also_ wonder whether the total charges should be put up there as well for better visibility.

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/speciesTab.ui
Keeping the geometry terms in a separate dialog I think is definitely the way to go, but perhaps a summary of the number of each term type within the Atoms frame might be nice.

2023-07-10 09:55 UTC, trisyoungs commented on src/gui/speciesTab.ui
In the Atoms table we can reclaim a bit of useful space by calling the first to columns `El` and `AT`, and we should call resizeColumnsToContents() to get a minimised version on show.  Furthermore, we really don't need to display the element name, and we should just do the element symbol instead.

2023-07-11 15:20 UTC, trisyoungs approved these changes
I've updated the density icon and added one (supposed to) represent the periodic table for the empirical formula so we don't overuse the other icon. If we can add a tooltip explaining what the empirical formula frame is (i.e. "Empirical formula of the species") then I reckon we're done!

2023-07-11 19:47 UTC, merged