Empty Expressions and Fragment Descriptions
disorderedmaterials/dissolve pull request #1501
Opened 2023-07-06 17:08 UTC by jws-1

This slightly-hacky PR prevents segmentation faults occurring when NETA definition strings and expression strings in nodes are empty. Closes #1487.

2023-07-07 08:29 UTC, trisyoungs commented
Ignoring the swathe of broken unit tests for now (:grin:) I can also segfault Dissolve as simply as adding in a rogue backtick on to an expression, for example adding one on to the end of `rho` in my `AddNode` density keyword (heh - overly descriptive: try getting a backtick to display in code in a comment!) I get a `throw` of "Failed to evaluate expression ''.".  This shows up correctly as a red cross in the GUI, but is blindly ignored when you run the procedure.  So this is a bigger problem than perhaps anticipated.

I think the neatest solution would be to extend the `ProcedureNodeSequence::check()` to check any `NodeValue`-based keywords on each node for validity, calling the `check()` function before the procedure is executed.

2023-07-07 16:35 UTC, jws-1 commented
> Ignoring the swathe of broken unit tests for now (grin) I can also segfault Dissolve as simply as adding in a rogue backtick on to an expression, for example adding one on to the end of `rho` in my `AddNode` density keyword (heh - overly descriptive: try getting a backtick to display in code in a comment!) I get a `throw` of "Failed to evaluate expression ''.". This shows up correctly as a red cross in the GUI, but is blindly ignored when you run the procedure. So this is a bigger problem than perhaps anticipated.
> 
> I think the neatest solution would be to extend the `ProcedureNodeSequence::check()` to check any `NodeValue`-based keywords on each node for validity, calling the `check()` function before the procedure is executed.

While that does seem to solve the `backtick` problem, it doesn't solve the issue of empty expressions and expressions with periods and no numbers. Both issues occur as `isNumber` returns true, and then `std::stod` and `std::stoi` throw `std::invalid_argument`.

2023-07-10 09:15 UTC, trisyoungs requested changes

2023-07-10 09:15 UTC, trisyoungs commented on src/procedure/nodes/sequence.cpp
> +                return false;
Just adding a couple of other `NodeValue`-based classes, and to note that these must reference the keyword class, not the datatype.  Code not tested, BTW!
```suggestion

        // Check validity of NodeValue-based keywords
        for (auto &kwd : node->keywords().allOfType<NodeValueKeyword>())
            if (!kwd->data().isValid())
                return false;
        for (auto &kwd : node->keywords().allOfType<Vec3NodeValueKeyword>())
            if (!kwd->data().x.isValid() || !kwd->data().y.isValid() || !kwd->data().z.isValid())
                return false;
        for (auto &kwd : node->keywords().allOfType<NodeValueEnumOptionsBaseKeyword>())
            if (!kwd->value().isValid())
                return false;
```

2023-07-10 09:57 UTC, jws-1 commented on src/procedure/nodes/sequence.cpp
> +                return false;
Oops.. still familiarising myself with the `NodeValue` stuff.

2023-07-10 11:43 UTC, trisyoungs approved these changes
:+1:

2023-07-10 11:43 UTC, trisyoungs commented on src/base/sysFunc.cpp
> +    isFloatingPoint &= nDigits > 0;
Bit witchcraft!

2023-07-10 12:22 UTC, merged