1528 Input File Error Handling
disorderedmaterials/dissolve pull request #1532
Opened 2023-07-12 13:22 UTC by trisyoungs

This PR significantly "softens" the assumed severity of errors encountered while reading our (current) input file format. Wherever possible errors are simply reported, but parsing continues, and should greatly reduce the amount of bad UX when loading in a slightly older input file.

Closes #1528.

2023-07-14 09:03 UTC, jws-1 requested changes
I like where this is going, and it works nicely! However, I noticed that when parsing a `Procedure` if a keyword within a Node has an invalid number of parameters, the error propagates through the rest of the sequence. The rest of the sequence will be parsed correctly, but the error messages suggest otherwise.

![image](https://github.com/disorderedmaterials/dissolve/assets/100244619/3201c15d-9290-415f-8373-056b6025711f)

2023-07-17 08:29 UTC, trisyoungs commented
Good spot.  Have modified files accordingly to prevent all these spurious errors!

2023-07-17 09:23 UTC, jws-1 approved these changes
Looks good to me now. However, I wonder if we should also set `errorsEncountered` when an invalid keyword is given - for example see my comment on `species_io.cpp`

2023-07-17 09:23 UTC, jws-1 commented on src/procedure/nodes/sequence.cpp
> +    return !errorsEncountered;
```suggestion
    return (!errorsEncountered);
```
For consistency

2023-07-17 09:23 UTC, jws-1 commented on src/procedure/nodes/node.cpp
> +    return !errorsEncountered;
```suggestion
    return (!errorsEncountered);
```
Consistency

2023-07-17 09:23 UTC, jws-1 commented on src/classes/species_io.cpp
> +        }
Should we also set `errorsEncountered = true` here?

2023-07-18 16:03 UTC, trisyoungs commented on src/classes/species_io.cpp
> +        }
Yes, and in a bunch of other similar places.

2023-07-20 11:26 UTC, merged