Zip iterator
disorderedmaterials/dissolve pull request #514
Opened 2021-01-12 17:47 UTC by rprospero

This adds a zip iterator for looping over multiple lists simultaneously.  There's several example of its usage added (though not even close to every possible instance).  However, the general idea is to replace

```
for(int n=0; n<xs.size(); ++n) {
    auto x = xs[n];
    auto y = ys[n];
```

with

```
for(auto&& [x, y] : zip(xs, ys)) {
```

2021-01-13 15:39 UTC, trisyoungs requested changes
This is good - makes a lot of sense seeing it used in context in the code. Some minor comments in the review, and I can't fully unpick the mechanism of the `operator!=` in `ZipIterator`, but I trust that it's doing the right thing!

2021-01-13 15:39 UTC, trisyoungs commented on src/io/export/data1d.cpp
> +            if (!parser.writeLineF("{:16.10e}  {:16.10e}  {:16.10e}\n", n, value, error))
From a style / readability perspective, I would rather grab the x-axis vector as `xAxis` rather than (my old) `x`, and then use `x` as the loop variable rather than `n`.  `n` conveys a certain `int`-like quality to me (probably thanks to Fortran...)

2021-01-13 15:39 UTC, trisyoungs commented on src/io/export/data1d.cpp
> +            if (!parser.writeLineF("{:16.10e}  {:16.10e}\n", n, value))
And here.

2021-01-13 15:39 UTC, trisyoungs commented on src/math/data1d.cpp
> +            if (!parser.writeLineF("{}  {}\n", n, value))
Similarly, `n` could be `x` here.

2021-01-13 15:39 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +            for (auto sq : estimatedSQ)
```suggestion
            for (auto &sq : estimatedSQ)
```

2021-01-13 15:39 UTC, trisyoungs commented on src/templates/algorithms.h
> +    std::tuple<Args &...> sources;
```suggestion
    std::tuple<Args &...> sources_;
```
For consistency with member visibility elsewhere.

2021-01-13 15:39 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +                    val *= old / nw;
Presumably the arguments in the tuple are all extracted from the source vectors by reference, so this kind of in-place modification will work as expected?

2021-01-13 15:53 UTC, rprospero commented on src/modules/epsr/process.cpp
> +                    val *= old / nw;
It does allow for in place updates.  That's one of the things I made sure to check when I wrote the unit tests.

2021-01-13 16:02 UTC, rprospero commented on src/io/export/data1d.cpp
> +            if (!parser.writeLineF("{:16.10e}  {:16.10e}  {:16.10e}\n", n, value, error))
`x` is obviously the better name there.

2021-01-14 09:13 UTC, trisyoungs approved these changes

2021-01-14 11:43 UTC, merged