It compiles, but tests do not pass
disorderedmaterials/dissolve pull request #543
Opened 2021-02-15 10:30 UTC by rprospero

2021-02-17 09:56 UTC, trisyoungs requested changes
Some minor function naming suggestions and other bits, but all looks good.

2021-02-17 09:56 UTC, trisyoungs commented on src/classes/coredata.cpp
> +    return {};
Here it would be better to rename the `hasMasterBond` (my original name, I know!) to `getMasterBond` as it is a getter, and have a separate `hasMasterBond` function that returns just a `bool`. This would be consistent with function names/return types used in the majority of other places in the code.

2021-02-17 09:56 UTC, trisyoungs commented on src/classes/coredata.cpp
> +OptionalReferenceWrapper<MasterIntra> CoreData::hasMasterAngle(std::string_view name)
Same here.

2021-02-17 09:56 UTC, trisyoungs commented on src/classes/coredata.cpp
>      return b;
Tempting to add a constructor with default `name` and `type` args to `MasterIntra` so that this (and the other related occurrences) can be reduced to `masterBonds_.emplace_back(name, SpeciesIntra::BondInteraction);` followed by `return masterBonds_.back();`.

2021-02-17 09:56 UTC, trisyoungs commented on src/classes/coredata.h
> +    MasterIntra &masterBond(int n);
I don't think this is used anywhere now, so can be removed along with the related calls for angle, torsion, and improper.

2021-02-17 09:56 UTC, trisyoungs commented on src/classes/masterintra.cpp
>  MasterIntra::~MasterIntra() {}
Make this a `default` dtor.

2021-02-17 09:56 UTC, trisyoungs commented on src/classes/speciesintra.cpp
> +    form_ = source.form_;
Good catch.  Not quite sure what the effect of this would have been!

2021-02-17 09:56 UTC, trisyoungs commented on src/gui/importspecieswizard_funcs.cpp
> +        if (dissolveReference_->coreData().findMasterTerm(intra.name()))
We're missing a check for the improper terms here (my fault).

2021-02-17 09:56 UTC, trisyoungs commented on src/gui/keywordwidgets/modulegroups_funcs.cpp
> -    auto &groups = keyword_->data();
Why not `auto` here?

2021-02-19 13:38 UTC, rprospero commented on src/classes/coredata.cpp
>      return b;
That makes the code much cleaner.

2021-02-19 14:32 UTC, rprospero commented on src/classes/coredata.h
> +    MasterIntra &masterBond(int n);
It might be worth looking for a decent dead-code elimination tool

2021-02-19 14:40 UTC, rprospero commented on src/classes/masterintra.cpp
>  MasterIntra::~MasterIntra() {}
Done

2021-02-19 14:43 UTC, rprospero commented on src/gui/importspecieswizard_funcs.cpp
> +        if (dissolveReference_->coreData().findMasterTerm(intra.name()))
Good catch

2021-02-19 14:46 UTC, rprospero commented on src/gui/keywordwidgets/modulegroups_funcs.cpp
> -    auto &groups = keyword_->data();
That should obviously be `auto`.  I'm wondering if maybe I had briefly messed with the return type of `data` and I needed to use an explicit type to properly cast out of a reference wrapper?

2021-02-19 15:11 UTC, rprospero commented on src/classes/coredata.cpp
> +    return {};
I've renamed all of the `hasMaster` functions to `getMaster`.  I have *not* yet added in the new, `bool`-returning `hasMaster` functions.  My reasoning is that the only places in the code that we'd be using the new `hasMaster` is within the `CoreData` class itself.  That would tend to imply that the new methods should be `private`, but it felt kind of odd to add a private wrapper around a classes own method, especially since the `getMaster` method can be use in place with now changes.

If we think that `hasMaster` will become more important, I'm happy to add it in, but I've left it out for now.

2021-02-22 09:35 UTC, merged