Range splitter
disorderedmaterials/dissolve pull request #555
Opened 2021-02-25 11:40 UTC by rprospero

Use a general range splitter during MPI instead of using a stride step.  This will make it easier to switch to using algorithms, since they always look at every element.

2021-03-01 10:52 UTC, trisyoungs requested changes
Definitely heading in the right direction, but need to take a close look at a couple of bits.

2021-03-01 10:52 UTC, trisyoungs commented on src/templates/algorithms.h
> +template <typename T> auto cut_range(const T begin, const T end, const int count, const int step)
Should `count` represent the number of "chunks" (processors) and `step` the current index of the chunk/process? If so, names could be more descriptive.

Also, is this more appropriately named `chop_range` than a `cut_range`?

2021-03-01 10:52 UTC, trisyoungs commented on src/templates/algorithms.h
> +    return std::make_tuple(start, stop);
Shouldn't the `step` multiply against `count` rather than `diff`?  And how is the remainder handled when the number of elements in the array doesn't divide evenly over processes?

2021-03-01 14:07 UTC, rprospero commented on src/templates/algorithms.h
> +    return std::make_tuple(start, stop);
Multiplying against `diff` is the correct value and is how the remainder is handled.  For example, if you have a five element array and a count of 3.

step 0 =>
start = (0 * 5) // 3 = 0 // 3 = 0
stop = 1*5 // 3 = 5 // 3 = 1

step 1 =>
start = (1 * 5) // 3 = 1 // 3 = 1
stop = 2*5 // 3 = 10 // 3 = 3

step 2 =>
start = (2 * 5) // 3 = 10 // 3 = 3
stop = 3*5 // 3 = 15 // 3 = 5

2021-03-01 14:50 UTC, rprospero commented on src/modules/rdf/functions.cpp
> +        for_each_pair(ri, ri + maxr[typeI], stride, start,
I believe that the code should follow the same semantics as the original code.  Each `typeI` is followed in the outer loop.  The inner loops finds the distances for each pair in `ri`.  So it will calculate the upper-right triangular element for the entire range.

2021-03-01 15:50 UTC, trisyoungs commented on src/modules/rdf/functions.cpp
> +        for_each_pair(ri, ri + maxr[typeI], stride, start,
OK. Sorry - rushed to go through this before home schooling started!

2021-03-01 15:51 UTC, trisyoungs commented on src/templates/algorithms.h
> +    return std::make_tuple(start, stop);
Again, apologies - not firing on all cylinders today.

2021-03-04 16:48 UTC, trisyoungs approved these changes

2021-03-09 17:35 UTC, merged