TEMPORARY New GenericList
disorderedmaterials/dissolve pull request #586
Opened 2021-03-11 15:55 UTC by trisyoungs

See PRinfo file in root dir for details.

2021-03-11 16:42 UTC, StephenSmith25 reviewed
In general I think it seems like a reasonable solution. In my opinion, things like the producers should probably be abstracted out from the Generic List class at some point (maybe after you have a minimal working example) something like a factory class which handles registering and creation of the types would probably be a good idea. You could then have a singleton instance of this factory, that’s used for all the lists to create items. But I haven't considered the implementation any further than that.

I know you've kept away from boost, but I'm wondering if it would be worth looking at boost.fusion, https://theboostcpplibraries.com/boost.fusion, its a library that supports heterogeneous containers. Maybe it doesn't do everything you need (as I'm not really familiar with the GenericList yet) but I think it may be worth a glance.

2021-03-11 17:42 UTC, trisyoungs commented
The factory is a good idea - there is a clear separation between the creation of the items and the intent of the `GenericList`.

The Boost fusion stuff is cool and, if I understand it correctly, could allow this to be rewritten using templated functions instead of all this `std::any` business.  Overhead isn't really an issue here, but of course the Boost way would be faster.

2021-03-12 10:32 UTC, rprospero reviewed
Just taken a quick look through on this and it looks great.  I'll have to do a more thorough look later on.  I did make a couple of comments on places where we could better use some algorithms and my personal preference for destructuring binds, though I'm not going to fight for that one.

I think that there may be a better way to handle the broadcasters and serialisers through `std::visit` which would save the need to register, but I'll have to give that some more thought.

2021-03-12 10:32 UTC, rprospero commented on src/genericitems/list.cpp
> +            ++it;
```suggestion
    items_.erase(std::remove_if(items_.begin(), items_.end(), [=](auto& [key, value]){ return !(std::get<ItemData::Flags>(value) & GenericList::ProtectedFlag);}, items_.end());
```

Might need to take a closer look at what I've included in with the lambda, but I think I got that right.

2021-03-12 10:32 UTC, rprospero commented on src/genericitems/list.cpp
> +            items_.erase(it);
```suggestion
    items_.erase(std::remove_if(items_.begin(), items_.end(), [&suffix](auto& [key, value]){ return DissolveSys::endsWith(key, suffix);}, items_.end());

```

2021-03-12 10:32 UTC, rprospero commented on src/genericitems/list.cpp
> +            continue;
```suggestion
    for (auto &[key, value] : items_)
    {
        // If it is not flagged to be saved in the restart file, skip it
        if (!(std::get<ItemData::Flags>(value) & GenericList::InRestartFileFlag))
            continue;
```

It's a style thing, but I happen to like using the destructuring binds to give names to the individual parts

2021-03-12 10:32 UTC, rprospero commented on src/genericitems/list.cpp
> +            return false;
```suggestion
        if (!parser.writeLineF("{}  {}  {}  {}  {}\n", headerPrefix, key, std::get<ItemData::ClassName>(value),
                               std::get<ItemData::Version>(value), std::get<ItemData::Flags>(value)))
            return false;
```

Names again

2021-03-12 10:32 UTC, rprospero commented on src/genericitems/list.cpp
> +        auto &data = std::get<ItemData::AnyObject>(item.second);
```suggestion
        auto &data = std::get<ItemData::AnyObject>(value);
```

2021-03-12 10:32 UTC, rprospero commented on src/genericitems/list.cpp
> +                            item.first, std::get<ItemData::ClassName>(item.second))));
```suggestion
                            key, std::get<ItemData::ClassName>(value))));
```

2021-03-12 10:32 UTC, rprospero commented on src/genericitems/list.cpp
> +            return Messenger::error(fmt::format("Broadcast of item '{}' failed.\n", item.first));
```suggestion
    for (auto &[key, value] : items_)
    {
        Messenger::printVerbose("Broadcasting item '{}'...\n", key);
        auto &data = std::get<ItemData::AnyObject>(value);
        auto it = broadcasters_.find(data.type());
        if (it == broadcasters_.end())
            throw(std::runtime_error(
                fmt::format("Item '{}' cannot be broadcast as no suitable broadcaster is available (for '{}').\n", key,
                            data.type().name())));
        if (!(it->second)(data, procPool, root, coreData))
            return Messenger::error(fmt::format("Broadcast of item '{}' failed.\n", key));
```

2021-03-12 10:32 UTC, rprospero commented on src/genericitems/producers.cpp
> +    registerProducer<Vec3<double>>("Vec3<double>");
There's a beautiful bit with consteval and fragments coming in c++23 that will handle this boilerplate for us.  I'm sure that we'll get c++23 support on SCARF in just a couple more popes.

2021-03-12 11:18 UTC, trisyoungs commented on src/genericitems/list.cpp
> +            continue;
Much nicer!

2021-03-12 11:19 UTC, trisyoungs commented on src/genericitems/list.cpp
> +            ++it;
For some reason I was under the impression that `std::map` didn't have an `erase()` overload that took begin and end iterators.  It's been a tough week!

2021-03-12 11:22 UTC, trisyoungs commented on src/genericitems/producers.cpp
> +    registerProducer<Vec3<double>>("Vec3<double>");
Bring on FRANCISCVS Tertium!

2021-03-12 11:28 UTC, trisyoungs commented
@rprospero if you can get `std::visit` to play ball with `std::any`, then that would be great.  I failed on what I thought were quite fundamental levels - I tried with a type-matching visitor of the type exemplified on https://en.cppreference.com/w/cpp/utility/variant/visit to avoid the need of a `std::variant`, but failed quickly as passing a `std::any` raises a `valueless_by_exception` error.  Sure, you can check the type at run time with `type()` but there's no way to translate that to a (compile-time) templated function call or cast it before passing to `std::visit`.  If you can unpick this, then I'm definitely listening!

2021-03-12 12:30 UTC, rprospero commented
That’s my mistake. You’re right that std::any and std::visit are fundamentally incompatible.  My original thought had been a giant std::variant (with a short and friendly alias).  That should work with std::visit, but would require every type that’s stored in the generic list to be manually included in the variant.  I’d suggested std::any to get around that, forgetting that I just broke std::visit.

I’m not sure that adding all the types to the variant and visit isn’t just as much boilerplate as registering all the types with visit.  I guess it might give more compile time type safety?

> On 12 Mar 2021, at 11:29, Tristan Youngs ***@***.***> wrote:
> 
> ﻿
> @rprospero if you can get std::visit to play ball with std::any, then that would be great. I failed on what I thought were quite fundamental levels - I tried with a type-matching visitor of the type exemplified on https://en.cppreference.com/w/cpp/utility/variant/visit to avoid the need of a std::variant, but failed quickly as passing a std::any raises a valueless_by_exception error. Sure, you can check the type at run time with type() but there's no way to translate that to a (compile-time) templated function call or cast it before passing to std::visit. If you can unpick this, then I'm definitely listening!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-12 13:23 UTC, trisyoungs commented
I had considered the catch-all `std::variant` as the alternative solution, but I don't really like the fact that the variant takes on the size of the largest container, so storing a `bool` whose memory footprint is that of a `ALargeClass` doesn't sit well with me.  Sure, the overall amount of memory wastage is probably small right now, but it will only grow.

2021-03-12 14:27 UTC, trisyoungs commented
> Just taken a quick look through on this and it looks great. I'll have to do a more thorough look later on. I did make a couple of comments on places where we could better use some algorithms and my personal preference for destructuring binds, though I'm not going to fight for that one.

Alas, when using iterators you can't use a structured bind.

2021-03-25 11:46 UTC, rprospero requested changes
I've made some suggestions that might clean up a bunch of the boilerplate around registering the various helper functions.

2021-03-25 11:46 UTC, rprospero commented on src/genericitems/producers.h
> +    }
```suggestion
    template <class T> void registerProducer()
    {
        producers_[typeid(T)] = []() { return T(); };
        classNames_[typeid(T)] = std::move(typeid(T).name());
    }
```

This would remove the need to give the type name in both the template and the string for every type.  It does remove the ability to register a producer under the "wrong" name, but I didn't find an instance of using that.

2021-03-25 11:46 UTC, rprospero commented on src/genericitems/producers.cpp
> +    registerProducer<Array<double>>("Array<double>");
```suggestion
    registerProducer<Array<double>>();
```

This change goes with the change I suggested to `registerProducer` in producers.cpp.  The same change would obviously be applied to all the following lines.

2021-03-25 11:46 UTC, rprospero commented on src/genericitems/producers.cpp
> +}
```suggestion
std::string GenericItemProducer::className(const std::type_info &objectType) const
{ return objectType.name(); }
```

This follows from my suggested change to the registration function.  I guess it could be a problem if we're using that exception for flow control elsewhere in the program, but I'm really hoping that we're not.

2021-03-25 11:46 UTC, rprospero commented on src/genericitems/serialisers.cpp
> +    });
Further down, I'm going to bring up again the idea of doing the serialisation slightly recursively.    As an example of why I think that this is important, I've noticed that, for a vector of doubles, the values are all formatted `{:16.9e}`, but there's no such formatting for a raw double.  Is this inconsistency intentional?  Using the recursive method would prevent it from occuring.

2021-03-25 11:46 UTC, rprospero commented on src/genericitems/serialisers.cpp
> +    });
```suggestion
    registerSerialiser<std::vector<double>>([](const std::any &a, LineParser &parser, const CoreData &coreData) {
        const auto &v = std::any_cast<const std::vector<double> &>(a);
        if (!parser.writeLineF("{}\n", v.size()))
            return false;
        for (auto &n : v)
            if (!serialiseObject(n, parser, coreData))
                return false;
        return true;
    });
```

Just as with the deserialisers, I think it could be useful to go slightly recursive here.  I've mentioned before that we already have an inconsistency, plus this would be more useful on some of the later classes (example to follow).

2021-03-25 11:46 UTC, rprospero commented on src/genericitems/serialisers.cpp
> +                    return false;
```suggestion
            if (!serialiseObject(data, parser, coreData))
                return false;
```

A bigger example of the advantages of the recursive route.

2021-03-25 11:46 UTC, rprospero commented on src/genericitems/serialisers.cpp
> +    });
```suggestion
    registerSerialiser<AtomTypeList>(simpleSerialise<AtomLtypeList>);
```

Like my suggestion with the deserialiser, this would require making another function

```
template <class T>
bool simpleSerialise(const std::any &a, lineParser &parser, const CoreData &coreData) {
    return std::any_cast<const T &>(a).serialise(parser);
}
```

2021-03-25 12:13 UTC, trisyoungs commented on src/genericitems/deserialisers.cpp
> +
It's a good suggestion.  I know we talked a long time ago about replacing the custom `LineParser` with a more general lib though, so this probably gets consumed under that as well.

2021-03-25 12:13 UTC, trisyoungs commented on unit/test_genericlist.cpp
> +
:+1:

2021-03-25 12:23 UTC, trisyoungs commented on src/genericitems/deserialisers.cpp
> +    });
:+1:

2021-03-25 12:24 UTC, trisyoungs commented on src/genericitems/deserialisers.cpp
> +    });
Good suggestion - worth a try!

2021-03-25 12:25 UTC, trisyoungs commented on src/genericitems/producers.h
> +    }
Unfortunately, since type names derived from `type_info` are implementation-dependent and often mangled, this would break restart-file compatibility across platforms. So, for consistency the manual naming approach has to remain.

2021-03-25 12:27 UTC, trisyoungs commented on src/genericitems/serialisers.cpp
> +    });
No reason for the inconsistency at all, and another benefit to your original suggestion.

2021-03-25 13:12 UTC, rprospero commented on src/genericitems/producers.h
> +    }
Good call.  I haven't considered the cross platform issues.

2021-03-25 13:13 UTC, rprospero commented on src/genericitems/producers.cpp
> +    registerProducer<Array<double>>("Array<double>");
Obviously not possible the the cross platform issues that we discussed.

2021-03-25 13:13 UTC, rprospero commented on src/genericitems/producers.cpp
> +}
Again, not safely cross-platform.

2021-03-25 14:11 UTC, trisyoungs commented on src/genericitems/deserialisers.cpp
> +    });
Looking at how this change works under the hood, this would involve at the very least retrieving the relevant function from the `deserialiers_` `std::map` - for a single `double` that isn't an issue, but performance may start to suffer if we write containers (of containers) of `double`s this way. Same goes for the serialisers below. I'd probably suggest that we keep the explicit read/write of PODs as they are (with consistent formatting, of course) and utilise the recursion only for `class` objects (e.g. `Array<Data1D>`).

2021-03-25 15:09 UTC, trisyoungs commented on src/genericitems/deserialisers.cpp
> +    });
This works very nicely.  Had to create two static template functions for the deserialisers, as some don't take the `CoreData` arg, but that's only a minor inconvenience.

2021-03-25 15:22 UTC, rprospero commented on src/genericitems/deserialisers.cpp
> +    });
That feels like the proper compromise.

2021-03-26 16:33 UTC, StephenSmith25 approved these changes
All looks good to me, just some minor things I spotted.

2021-03-26 16:33 UTC, StephenSmith25 commented on src/genericitems/serialisers.cpp
> +    return _instance;
Nitpicky but I think google coding standards would avoid a leading underscore in a variable name.

2021-03-29 09:33 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +    bool created;
Indeed it is not.  Found a few others as well...

2021-03-29 09:33 UTC, trisyoungs commented on src/procedure/nodes/collect2d.cpp
>      bool created;
:+1:

2021-03-29 09:35 UTC, trisyoungs commented on src/genericitems/serialisers.cpp
> +    return _instance;
To be honest, I'm not sure why I used them in the first place! Now removed.

2021-03-29 11:47 UTC, merged