Incorporate TBB in calculateGRCells method (DRAFT)
disorderedmaterials/dissolve pull request #611
Opened 2021-03-23 13:45 UTC by StephenSmith25

This PR implements some TBB into the GR calculation for the cells based method. It does this by doing a parallel loop over the cell combinations. The intention was to use the parallel STL algorithms, but OSX doesn't support this yet. Therefore I've had to use TBB.

Everything's a bit all over the place at the moment. but I would appreciate any comments - suggestions - anything! One thing to note is that I've had to create a `TempHistogram` struct as the object store sometimes leads to an exception being thrown by one of the threads (I guess its not thread safe?) if I use HIstogram1D.

From my own rudimentary timings, i.e. including `chrono` and measuring the time it seems faster.

2021-03-24 09:23 UTC, trisyoungs reviewed
Looking promising!  Some general comments:

1. If `clang` on OSX is going to be an issue, can anyone think of a particular reason why we wouldn't move to using `gcc` instead, and going with `<parallel>`?
2.  How does this compare with the MPI version?
3. The new `Combinations` class, if I read it correctly, gives you all the unique pairs of indices in one diagonal half of the square matrix, and *excludes* the on-diagonal (`i` == `j`) elements?  I know this is a rough draft, but comments in the file should reflect this as this is different to `for_each_pair`, for instance, which includes the on-diagonal elements.
4. The Dissolve blueprint did not consider thread safety since MPI was the assumed parallel architecture. When you say the "object store" is complaining when using `Histogram1D`, are you referring to the `ObjectStore` class? I haven't checked at which point your repo is currently even with, but as you have probably seen the `ObjectStore` class is halfway in the bin already...

2021-03-24 09:23 UTC, trisyoungs commented on CMakeLists.txt
> +include_directories(${TBB_INCLUDE_DIRS})
If we end up having to "manually" use TBB, this can go into `conanfile.txt`.  The linkage can then also be done in `target_link_libraries` (around line 279) following the convention for the `fmt` and `CLI11` packages.

2021-03-24 09:23 UTC, trisyoungs commented on src/math/histogram1d.cpp
> +    nMissed_ += other.nMissed_;
Good catch!

2021-03-24 09:23 UTC, trisyoungs commented on src/math/histogram1d.cpp
> +        ret.bins_[n] += other.bins_[n];
Could use `std::transform` here.

2021-03-24 11:05 UTC, rprospero requested changes
This is some great work and I like what you did with the combinations class.  However, there's a couple of design notes that come into play here.

First, since we are going to be going with GCC on Mac, the hope is to stick with the STL <parallel> header and the standard <algorithms> and not directly invoke TBB.  Part of the reasoning behind this is that the algorithms are also an inspiration for some of the GPU libraries that we've been looking at and we were hoping that the multi-core parallelism would be a stepping stone toward GPU usage.

Along those lines, while I love the combinations class, we're trying to move away from raw integer indices where possible, especially since there will wind up being a lot of duplicate code as we use this across the many places that we hope to eventually parallelize.  I think that we could have a `CombinationsIterator`  function that could keep track of where it was in the iteration.  Under the hood, it'd probably just be a link to the `begin` and `end` positions along with a `Combinations` object to keep track of the position.

Finally, I noticed that `getCoefficient` was ultimately a double loop (looping over `nChooseK`, which itself contains a loop).  That initially bothered me, since this would be a double loop at every single position.  However, since we only use k=1 and k=2, the loops are very short.  I've already included a loopless version of `nChooseK`.  I suspect that the same is possible for `getCoefficient`.  We could even split it into `getCoefficient1` and `getCoefficient2` and remove the `k` parameter entirely, so we don't have to worry about the error case when k isn't 1 or 2.

I'm happy to talk it over if you have alternate design ideas.  I've asked for a **lot** here and I'm not trying to make work for you, so I'd be happy to hear your thoughts on other ways of doing this.  Including arguing for the code you already have!

2021-03-24 23:58 UTC, trisyoungs commented on unit/test_combination.cpp
> +        for (int j = i + 1; j < numTests; ++j)
Well, we may want the self-pairing case in some of the algorithms we parallelise, but in others we may not.  Energy, force, and RDF calculation can all exclude the `i == j` pair, but there will be others that that do require the self-pairing case. My original comment was to just clarify in the commenting which case the combinations were covering.

2021-04-02 15:27 UTC, trisyoungs reviewed
Liking where this is heading. :+1:

I had to manually compile both `gtest` and `tbb` in the `conan install` command (I upgraded `conan` itself to 1.35 first) - not a big deal, but something to remember once we incorporate this build into a pipeline on Azure. Furthermore, on my system at least the `pstl` headers are named differently, so I had to change the include lines to `#include <pstl/algorithm_impl.h>` and `#include <pstl/execution_impl.h>`. Obviously this is going to be annoying, and probably necessitates some platform-specific `#ifdef`s - this is another good reason to break out all the parallel-related includes into a separate, includable file.
P

However, I was unable to get the code to run properly! It seems that I get a hang in the code after the partials have been calculated, so the last output I see is:

```
Finished calculation of partials (4.19 seconds elapsed, 0.00 seconds comms).
Finished calculation of intramolecular partials (0.00 seconds elapsed, 0.00 seconds comms).
```

The threading is definitely working (according to the CPU usage anyway). This is the Linux CLI version, rather than the GUI, but I don't see why that would make a difference!

2021-04-06 11:37 UTC, StephenSmith25 commented on src/modules/rdf/functions.cpp
> +    RDFModuleHelpers::combinePartialHistogramsIntoPartialSet(partialSet, histograms);
No good reason whatsoever, I've now added it as a member function of the partial histograms.

2021-04-06 11:38 UTC, StephenSmith25 commented on src/modules/rdf/parallel_helpers.h
> +// store while in the parallel computations
I'll create an issue for this, as it would be good to revisit it and replace the temporary histogram with the normal histogram.

2021-04-06 11:42 UTC, StephenSmith25 commented
> Liking where this is heading. 👍
> 
> I had to manually compile both `gtest` and `tbb` in the `conan install` command (I upgraded `conan` itself to 1.35 first) - not a big deal, but something to remember once we incorporate this build into a pipeline on Azure. Furthermore, on my system at least the `pstl` headers are named differently, so I had to change the include lines to `#include <pstl/algorithm_impl.h>` and `#include <pstl/execution_impl.h>`. Obviously this is going to be annoying, and probably necessitates some platform-specific `#ifdef`s - this is another good reason to break out all the parallel-related includes into a separate, includable file.
> 
> However, I was unable to get the code to run properly! It seems that I get a hang in the code after the partials have been calculated, so the last output I see is:
> 
> ```
> Finished calculation of partials (4.19 seconds elapsed, 0.00 seconds comms).
> Finished calculation of intramolecular partials (0.00 seconds elapsed, 0.00 seconds comms).
> ```
> 
> The threading is definitely working (according to the CPU usage anyway). This is the Linux CLI version, rather than the GUI, but I don't see why that would make a difference!

Thanks for all the comments. I've separated out the tbb stuff now. Wondering why its hanging for you though! I've only been running it through the benchmark examples and the rdfmethod tests. So likely I've missed something. Also, I'm confused that you have to build the tbb package, seem there should be a prebuilt configuration for gcc 🤔

2021-04-06 17:25 UTC, trisyoungs commented
> Wondering why its hanging for you though! I've only been running it through the benchmark examples and the rdfmethod tests. 

Not sure, and I didn't have time to investigate it fully, but I'll definitely spend some time on that to see why it happens.

> Also, I'm confused that you have to build the tbb package, seem there should be a prebuilt configuration for gcc

Me too. I had to upgrade gcc 9.3 alongside 7.3 (for some reason there is a hard dependency between that particular version and the Qt libs on OpenSuSE) and then write a `conan.profile` so its possible I just missed something trivial.  Either way, it wasn't a massive inconvenience.

2021-04-13 22:37 UTC, trisyoungs commented
Update from a second look at this:

1. I didn't have to compile `gtest` and `tbb` this time.  Go figure!
2. I also didn't have to modify the include paths. Guess I (or my laptop) was having a bad day before.
3. The hang still occurs, and appears to be rooted in the `for_each_pair` loop starting on line 455 of `modules/rdf/functions.cpp`. From some initial testing, the loop seems to complete the first iteration, and then hangs (or segfaults if you're lucky...).

2021-04-27 08:40 UTC, trisyoungs approved these changes

2021-04-27 08:41 UTC, rprospero approved these changes

2021-04-27 09:07 UTC, merged