Adding Google benchmark and some initial benchmarks
disorderedmaterials/dissolve pull request #624
Opened 2021-04-01 15:32 UTC by StephenSmith25

Adding Google benchmark and setting some initial problems. The test problem has partially been hacked together from what "main" is doing, I'm guessing theres probably a better way to do a lot of these things. 

But just pushing up to get some feedback on whether this is something we'd want.

To use it add `-DBUILD_BECHMARKS:bool=true`

Then once they are built they can be run with 
`./bin/benchmark_Box `

And to output timing results (might be useful for keeping track of performance over time)

`./bin/benchmark_Box --benchmark_out=....`

2021-04-04 17:54 UTC, trisyoungs reviewed
Good start on some proper benchmarking here. One question is "Where is an appropriate place to store the benchmarking results?". Looking forward, we could entertain the idea of running these as part of a CI pipeline - for example, we could leverage this [GitHub Action for Continuous Benchmarking](https://github.com/rhysd/github-action-benchmark) to run on PR/develop triggers and provide performance information on specific commits. This action stores the results as a GitHub Pages deployment and provides decent-looking graphs of the results.  Since we no longer use Pages for anything, this could be a possibility.

One other thing - the new CMake flag (`-DBUILD_BENCHMARKS`) should be added to the compilation doc (https://github.com/disorderedmaterials/dissolve/blob/develop/web/content/docs/startingout/compilation.md).

2021-04-04 17:54 UTC, trisyoungs commented on benchmark/Box/benchmarks.cpp
> +        MonoclinicBox box(lengths, M_PI_4);
These ctors all take angles in degrees rather than radians, although of course these boxes are still valid (if a little on the slim side!).

2021-04-04 17:54 UTC, trisyoungs commented on benchmark/CMakeLists.txt
> +target_include_directories(benchmark_Box PRIVATE ${PROJECT_SOURCE_DIR}/src)
Since the list of benchmarks will grow, it's probably best to encapsulate all this code in a CMake macro, as we do for the system tests (`tests/CMakeLists.txt`).

2021-04-04 17:54 UTC, trisyoungs commented on benchmark/CalculateGR/test_problem.h
> +            dissolve_.loadInput("water10k.txt");
I was getting segfaults on running this benchmark until I realised that it couldn't find the input file! Is messaging disabled for performance reasons?

On a more general note, where is a good place for the files to be located, and how can that location be passed to `loadInput()` so that the user (or an automated test system) can find them?

It may also be an idea to modify these input files to contain only the bare bones of the system - specifically, just the `Species`, `Forcefield` and `Configuration` definitions. The modules providing the benchmarkable code can then be added by hand (as you do in this example).

2021-04-04 17:54 UTC, trisyoungs commented on benchmark/CalculateGR/test_problem.h
> +        cfg_ = benchmarkModule->targetConfigurations().first()->item();
```suggestion
        auto &procPool = dissolve_.worldPool();
        cfg_ = dissolve_.configurations().first();
```

2021-04-04 17:54 UTC, trisyoungs commented on benchmark/CalculateGR/test_problem.h
> +        rdfRange = 5;
I assume that `rdfRange_` was reduced from the maximal value in order to limit the time required for the benchmark?  The specified range obviously is a significant parameter in the Cells-based RDF method, so we should be clear on what is a "representative" test in this sense.

2021-04-04 17:54 UTC, trisyoungs commented on benchmark/CalculateGR/test_problem.h
> +        dissolve_.processingModuleData().remove(fmt::format("{}//OriginalGR", cfg_->niceName()), rdfmodule_->uniqueName());
Be lazy:
```suggestion
        dissolve_.processingModuleData().clearAll();
```

2021-04-07 14:45 UTC, StephenSmith25 commented
> 
> 
> Good start on some proper benchmarking here. One question is "Where is an appropriate place to store the benchmarking results?". Looking forward, we could entertain the idea of running these as part of a CI pipeline - for example, we could leverage this [GitHub Action for Continuous Benchmarking](https://github.com/rhysd/github-action-benchmark) to run on PR/develop triggers and provide performance information on specific commits. This action stores the results as a GitHub Pages deployment and provides decent-looking graphs of the results. Since we no longer use Pages for anything, this could be a possibility.
> 
> One other thing - the new CMake flag (`-DBUILD_BENCHMARKS`) should be added to the compilation doc (https://github.com/disorderedmaterials/dissolve/blob/develop/web/content/docs/startingout/compilation.md).

I didn't notice that there was a GitHub action for this, looks promising - I've restructured everything to potentially accommodate this:

- Just a single executable for all the benchmarks
- The executable should (/maybe/hopefully) be able to find the benchmarks files as the correct path should be configured by cmake

2021-04-07 14:46 UTC, StephenSmith25 commented on benchmark/CalculateGR/test_problem.h
> +        rdfRange = 5;
Correct, was mainly just testing things out - I've change it back to the file specified value now.

2021-04-07 14:49 UTC, StephenSmith25 commented on benchmark/CalculateGR/test_problem.h
> +            dissolve_.loadInput("water10k.txt");
Messaging was disabled as both the benchmark library and dissolve were both writing to std out, meaning the messages were getting tangled together.  

It should hopefully be smarter about finding the files now.

2021-04-16 14:18 UTC, rprospero reviewed
I really like the look of all of this and it seems a great path forward.  I've included some of my standard bike-shedding about using standard algorithms, but some of that is just because I'm not sure how well I understand the random distributions.

It also seems like there's a couple of generated files being committed to source control.  Do these need to be here?

2021-04-16 14:18 UTC, rprospero commented on benchmark/array/array_benchmark.cpp
> +    }
```suggestion
    std::fill(array.begin(), array.end(), distribution(generator));
```

Okay, switching this over to an algorithm isn't really that important.  However, I was curious about whether the above code was actually correct or if this needs `std::generate`.  Basically, is each element supposed to have an identical distribution or are they supposed to be unique?

2021-04-16 14:18 UTC, rprospero commented on benchmark/array/array_benchmark.cpp
> +            array[{i, j}] = distribution(generator);
```suggestion
    std::generate(array.begin(), array.end(), [&](){return distriburion(generator);}); 
```

Went with `generate` here instead of `fill` because I don't know which one we're supposed to use here.  Also just somewhat showing off that you can iterate over the entire Array2D.

2021-04-16 14:18 UTC, rprospero commented on benchmark/array/array_benchmark.cpp
> +                array[{i, j, k}] = distribution(generator);
```suggestion
    std::fill(array.begin(), array.end(), distribution(generator));
```

Using `fill` again

2021-04-16 14:18 UTC, rprospero commented on benchmark/benchmark_config.h.in
> +/* DO NOT EDIT THIS FILE, IT IS AUTOGENERATED!
Does this file need to be under source control, since it's autogenerated?

2021-04-16 14:18 UTC, rprospero commented on benchmark/benchmark_results/MacbookPro_benchmark_Box.json
> +{
Do the benchmark results need to be under source control?  I'd presume that these files would be changing constantly.  Then again, there may be something I'm missing with the CI?

2021-04-18 08:20 UTC, trisyoungs requested changes
This is setting an excellent starting point for proper benchmarking of the code. Several comments point to extensions, but these should be left for subsequent PRs. On that note, it would be worth creating a sequence of issues for each extension, and an `Epic` issue to group them together.

One big area that should go in as a priority (but not in this PR) are benchmarks of various energy / force calculation routines.

2021-04-18 08:20 UTC, trisyoungs commented on benchmark/array/array_benchmark.cpp
> +    }
If the intent is to fill the array with a distribution of random `int`s, then `std::fill` is going to give an array full of the same `int`...

2021-04-18 08:20 UTC, trisyoungs commented on benchmark/array/array_benchmark.cpp
> +    std::shuffle(indicies.begin(), indicies.end(), generator);
Typo here and throughout - `indicies` should be `indices`.

2021-04-18 08:20 UTC, trisyoungs commented on benchmark/array/array_benchmark.cpp
> +            array[{i, j}] = distribution(generator);
I assume that this is the correct intent (note typo in `distriburion` in the suggestion).

2021-04-18 08:20 UTC, trisyoungs commented on benchmark/array/array_benchmark.cpp
> +                array[{i, j, k}] = distribution(generator);
Same caveat as mentioned above.

2021-04-18 08:20 UTC, trisyoungs commented on benchmark/benchmark_results/MacbookPro_benchmark_Box.json
> +{
I think that, given the intended route is to integrate via GH Actions, we shouldn't store this kind of results file directly in the main repo.

2021-04-18 08:20 UTC, trisyoungs commented on benchmark/calculate_gr/calculate_gr_benchmark.cpp
> +    }
```suggestion
    for (auto _ : state)
        problemDef.template iterateCells<method>();
```

2021-04-18 08:20 UTC, trisyoungs commented on benchmark/common/problems.h
> +    {
I understand that the `ProblemSize` enum here gives us a set of system sizes to apply the benchmarks to.  It would be nice to get a bit deeper in to this (perhaps not in this PR) - at present the stuff in `benchmark_files` (our base input files) comprise only atomic systems.  These are absolutely fine, but we should extend to molecular systems (this can be water and hexane for starters) to give a more rounded feel for algorithm performance over a variety of system types.

2021-04-19 08:10 UTC, StephenSmith25 commented on benchmark/benchmark_config.h.in
> +/* DO NOT EDIT THIS FILE, IT IS AUTOGENERATED!
Ah yes this comment is a bit misleading to be honest. The config.h.in file is configured by cmake into a config.h file which stores the location of the build folder (used for setting up path to benchmark files). This comment applies to the generated header file not the .in file.

2021-04-19 08:10 UTC, StephenSmith25 commented on benchmark/array/array_benchmark.cpp
> +    }
Yeah the intention is that all elements of the array are random integers.

2021-04-20 07:54 UTC, trisyoungs approved these changes

2021-04-20 09:06 UTC, merged