Parallel force calculations
disorderedmaterials/dissolve pull request #664
Opened 2021-05-04 13:31 UTC by StephenSmith25

This PR adds parallel force calculations and benchmarks. Performance look good, just comparing three of the macro benchmarks:

On my macbook pro quad core.
 |  Benchmark  |  Single threaded  |  Multithreaded | 
 |  ------------ |  ----------------- |  ------------- | 
 | BM_CalculateForces_TotalInterAtomic |  1524ms |  341ms
 | BM_CalculateForces_TotalIntraMolecular  |   42.4ms | 9.27ms
 | BM_CalculateForces_TotalForces |  1605 ms |  355ms

This PR also restructed the force kernel:

- References instead of shared ptr
- Remove storage of torision and angle parameters -> makes it easier to parallelize
- Most methods are now const -> implying some degree of thread safety

2021-05-05 08:29 UTC, trisyoungs requested changes
Looking really good. Only minor comments.

2021-05-05 08:29 UTC, trisyoungs commented on src/classes/forcekernel.h
> +    void addTorsionForceI(double du_dphi, int index, TorsionParameters &torisionParameters, ForceVector &f) const;
Type here `torisionParameters` -> `torsionParameters`.

2021-05-05 08:29 UTC, trisyoungs commented on src/classes/forcekernel.h
> +    void addTorsionForceL(double du_dphi, int index, TorsionParameters &torisionParameters, ForceVector &f) const;
And here.

2021-05-05 08:29 UTC, trisyoungs commented on src/classes/forcekernel.h
> +    void forcesWithMim(const Atom &i, const Atom &j, std::optional<double>, ForceVector &f) const;
Can we reinstate the variable names (`scale`) on the `optional` parameters. I get easily confused!

2021-05-05 08:29 UTC, trisyoungs commented on src/classes/potentialmap.cpp
> +}
If this completely replaces the `const std::shared_ptr<Atom>` version then that can be removed.

2021-05-05 08:29 UTC, trisyoungs commented on src/classes/potentialmap.cpp
> +
Same here.

2021-05-05 08:29 UTC, trisyoungs commented on src/modules/forces/process.cpp
> +                        auto torisionParameters = ForceKernel::calculateTorsionParameters(vecji, vecjk, veckl);
`torision`.

2021-05-05 08:29 UTC, trisyoungs commented on src/modules/forces/process.cpp
> +                        du_dphi = torsion.force(torisionParameters.phi_ * DEGRAD);
Question - is there any (performance) reason to prefer not copying / referencing these parameters out of the `torsionParameters` object, and just using the object, apart from readability? A shorter name for the object (e.g. `tp`) would help alleviate that.

2021-05-05 08:29 UTC, trisyoungs commented on src/classes/forcekernel.cpp
> +void ForceKernel::addTorsionForceI(double du_dphi, int index, ForceKernel::TorsionParameters &torisionParameters,
Mr `torision` again!

2021-05-05 08:29 UTC, trisyoungs commented on src/classes/forcekernel.h
> +    void forcesWithMim(const Atom &i, const Atom &j, std::optional<double>, ForceVector &f) const;
Also, it makes more sense to me to have the `optional` arg as the last parameter, since we're always specifying the `ForceVector`.

2021-05-05 10:58 UTC, StephenSmith25 commented on src/modules/forces/process.cpp
> +                        du_dphi = torsion.force(torisionParameters.phi_ * DEGRAD);
No good reason, both should give the same performance. I got a bit lazy and for some reason was utterly hopeless at writing the word `torsion`.. I've changed it to `tp` and removed these local variables.

2021-05-06 09:02 UTC, trisyoungs approved these changes

2021-05-06 12:11 UTC, merged