Speciestab model
disorderedmaterials/dissolve pull request #685
Opened 2021-05-14 10:17 UTC by rprospero

This PR moves all of the tables *except the Isotopologues* into a model/view system and adds unit tests.  There should be not behaviour changes from this, but it's worth a quick review of the behaviour.

This should close #600

2021-05-14 12:00 UTC, trisyoungs requested changes
Overall, looking really good. My only concerns that should be addressed is the editing of the items in the various tables:

1) Some time ago I made a change to the edit triggers on the tables, and after playing with the `SpeciesTab` a bit I really don't like it at all! At present we have all edit triggers enabled on items, including just clicking on one (that isn't currently selected). This immediately raises an editor delegate, when it feels entirely alien to do so.  If we could remove that trigger from all the tables, that would undo my bad decision and make the UX much nicer.

2) When a delegate is raised for an item on the table, the initial value is some default and not the current data in the table. For instance, numeric parameters all come up as `0` (or blank) and the functional form combos default to `None`. This is because the (custom) delegates used on those tables (see, e.g. `ExponentialSpinDelegate`) request their data via the `EditRole`, which isn't currently implemented as a return value.

2021-05-14 12:00 UTC, trisyoungs commented on src/gui/models/speciesAngleModel.cpp
> +    return 8;
There is of course a continuing "issue" with all of the tables on the `SpeciesTab` in that the number of parameters (and hence total number of columns) is not known unless we (dynamically) assess current functional forms of all the terms in the vector.  This is encapsulated by #597. This shouldn't be addressed as part of the current PR, but we may want to get on to it as a prioritised next step.

2021-05-14 12:00 UTC, trisyoungs commented on src/gui/models/speciesAngleModel.cpp
> +                                            : SpeciesAngle::angleFunctions().keywordFromInt(angle.form()).c_str();
Here and elsewhere, should we avoid `c_str()` and just use `QVariant::ftomStdString()`?

2021-05-14 12:00 UTC, trisyoungs commented on src/gui/models/speciesAtomModel.h
> +    void updateIsotopologuesTab();
This is a very specific name for a signal that could trigger a variety of events - perhaps a more general name, e.g. `dataChanged()`, might be more appropriate?

2021-05-14 12:00 UTC, trisyoungs commented on src/gui/speciestab.h
> +    // // Update Geometry tab
Double indent

2021-05-14 12:00 UTC, trisyoungs commented on src/gui/speciestab_funcs.cpp
> +      torsions_(species->torsions(), dissolve), impropers_(species->impropers(), dissolve)
Getting a `reorder` compiler warning - `angles_` and `bonds_` need to be swapped.

2021-05-14 12:00 UTC, trisyoungs commented on src/gui/speciestab_geometry.cpp
>      Locker refreshLocker(refreshLock_);
Redundant now.

2021-05-17 14:29 UTC, rprospero commented on src/gui/models/speciesAngleModel.cpp
> +    return 8;
I've gone ahead and assigned #597 to myself, as it's a natural follow on from this PR.

2021-05-17 14:51 UTC, rprospero commented on src/gui/models/speciesAngleModel.cpp
> +                                            : SpeciesAngle::angleFunctions().keywordFromInt(angle.form()).c_str();
I've moved all of the models to explicitly returning a `QString`, instead of having it implicitly cast from `c_str`.  The intent is clearer this way.

2021-05-17 15:16 UTC, rprospero commented on src/gui/models/speciesAtomModel.h
> +    void updateIsotopologuesTab();
I've switched this to `atomTypeChanged`.  This is because this is only trigged when the atom type changes, since this will propagate to the isotopologues table.  The `dataChanged` name was too general because there are many changes (e.g. changing the charge) that will not trigger the signal.  We could have used the pre-built `dataChanged` signal, but that would trigger a bunch of events on changes that weren't going to alter the table.

2021-05-18 09:06 UTC, trisyoungs approved these changes

2021-05-18 12:36 UTC, merged