Show all parameters in a single cell
disorderedmaterials/dissolve pull request #692
Opened 2021-05-18 12:53 UTC by rprospero

Instead of having four parameters displayed for each row, we display a single cell that has a comma separated list of the parameter values.  Eventually we'll want the parameters to be labelled, but that's a larger issue than the immediate interface one.

This closes #597.

2021-05-19 09:07 UTC, trisyoungs requested changes
After hacking around the bit that doesn't work for me (see sole comment on the code) this all looks fine, although I have to say that I much prefer a space following the comma in the list to break things up.

The same model can also be applied to the ForcefieldTab, perhaps in a subsequent PR.

2021-05-19 09:07 UTC, trisyoungs commented on src/gui/models/speciesModelUtils.cpp
> +}
This is the part that causes compilation errors for me as I _only_ have Qt 5.12.7, and the `QStringList` ctor you're using here wasn't introduced until 5.14. Who'd have though nobody needed it until then!

Since I'm pretty stuck with 5.12.7 and there are many other places in the code where a `", "`-separated list is required, I might suggest that this is a utility function to be added in a more general manner, perhaps in `DissolveSys`. Such a function could be something like:

```
std::string join_strings(Iter begin, Iter end, std::string_view glue, Lambda lam)
{
    return std::accumulate(std::next(begin), end, lam(*begin), [&lam](const auto &acc, const auto *item) { return fmt::format("{}{}{}", acc, glue, lam(*item)); };);
}
```
Invocation would then be:
```
auto joined = join_strings(source.parameters.begin(), source.parameters.end(), ", ", [](const auto value) { return fmt::format("{}", value); });
```

This should give enough flexibility for future use cases (e.g. "name=value" lists).

2021-05-19 10:18 UTC, rprospero commented on src/gui/models/speciesModelUtils.cpp
> +}
Ironically, that's what I had initially written, but I switched it over to the QStringList because I didn't like needing to check for the empty container. I had also assumed that it had been around since Qt 1, since it's so obvious.  I'll change it back.

2021-05-20 20:54 UTC, trisyoungs approved these changes
:+1: Like the use of `fmt::format` to give a general join function for probably all of the datatypes we'd ever need to be gluing together.

2021-05-21 08:47 UTC, merged