Parallel energy improvements
disorderedmaterials/dissolve pull request #701
Opened 2021-05-27 12:48 UTC by StephenSmith25

This PR improves the distribution of work in the energy parallelisation. 

It uses a precomputed matrix of neighbours, which is distributed over the threads. It means more of the work is parallel. Hopefully should have better scaling. Theres probably a few other places where the parallel work could be better distributed. 

My timings:

```
Benchmark before threading:

TotalInterAtomicMolecular<Medium> 2436ms

Before this PR but with threading

TotalInterAtomicMolecular<Medium> 391ms

Now,

TotalInterAtomicMolecular<Medium> 147ms
```

2021-05-27 20:14 UTC, trisyoungs requested changes
This is exactly the kind of thing I had in mind.

Couple of small comments, and one probably dumb question.

2021-05-28 09:23 UTC, StephenSmith25 commented on src/classes/energykernel.cpp
> +                                                     return runningTotal;
Yeah good point. But wasn't it doing this before? Maybe I'm missing something, but I looked at what it was doing before, which seemed to be:
- Loop over cells
- Call energy calculation of cell with itself
- Call energy calculation for its neighbours and mim neighbours. 

I'll rework it to account for the symmetry

2021-05-28 10:12 UTC, trisyoungs commented on src/classes/energykernel.cpp
> +                                                     return runningTotal;
Possibly, but that would have been wrong as well!  I'll have a check of this ahead of the TSC.

2021-05-28 16:01 UTC, StephenSmith25 commented
I've reworked how the energy is calculated for the cell array. It loops over the list of pairs (upper part of the matrix flattened as a 1d array) and finds the energy between the pairs of atoms in cells, rather than using the arrayIndex() method to omit repeated calculations. I've also pulled out the MPI distribution of the atoms in each pair of cells. I was thinking that the cells have already been distributed over MPI nodes and therefore we'd need to check if further distributing the atoms is beneficial.

2021-06-03 13:19 UTC, trisyoungs commented
Apologies - got carried away with a fix and, apparently, I have push access to your branch!  Terribly bad etiquette.

Here's the result anyway - I traced the crash back to `EnergyKernel::energy(const CellArray &cellArray ...)` in which the cell neighbour pairs seemed to refer to bad (deleted) pointers.  I couldn't see an obvious reason for this, but did realise that we didn't need to use a pointer-based array for `Cell` at all.  The array/vector is created once and never changes, so a plain `std::vector<Cell>` created to the known required size does the trick.  This clears up the crash, and as a by-product enforces that all pointers to `Cell`s returned by `CellArray` must be `const`.  The only caveat to this last point is when an atom needs to check its position to see if it has moved to a different cell.  I've put in a non-`const` overload of one of the access functions to get around that.

See what you think!

And again, apologies for trampling over your PR...

2021-06-07 13:41 UTC, StephenSmith25 commented
Thanks for looking at that! I pushed one further commit to make everything build - The vec3 constructor is now explicit as, `cell(1)` was ambiguous as it could either be `cell(int)` or `cell(vec3<>) `as a single integer can be implicitly converted into a vector, which should be avoided. Should be ready for a re-review.

2021-06-08 09:09 UTC, trisyoungs approved these changes
:+1:

2021-06-08 12:08 UTC, merged