Better import and export of PartialSet
disorderedmaterials/dissolve pull request #714
Opened 2021-06-07 14:48 UTC by rprospero

This includes a custom serialisation and parsing code for the PartialSet class.  This moves the Full, Bound, and Unbound terms into the same table, leading to a third as many lines and no repetition of the x-coordinate.  This should close #579.

2021-06-08 09:03 UTC, trisyoungs requested changes
Looks good.  Couple of small suggestions to consider

2021-06-08 09:03 UTC, trisyoungs commented on src/classes/partialset.cpp
> +                argIndex = readDataPoint(argIndex, parser, unbound);
Part of me wants to convert the x-axis value first and re-use it for clarity:
```suggestion
                auto x = parser.argd(argIndex++);
                part.xAxis().push_back(x);
                bound.xAxis().push_back(x);
                unbound.xAxis().push_back(x);
                argIndex = readDataPoint(argIndex, parser, part);
                argIndex = readDataPoint(argIndex, parser, bound);
                argIndex = readDataPoint(argIndex, parser, unbound);
```

2021-06-08 09:03 UTC, trisyoungs commented on src/classes/partialset.cpp
> +            auto nPoints = parser.argi(0);
Given we know the size, we could `reserve` the vectors in advance if we wanted to.

2021-06-09 09:23 UTC, rprospero commented on src/classes/partialset.cpp
> +            Messenger::warn("Tags: {} {} {}", parser.argsv(0), parser.argsv(1), parser.argsv(2));
Good catch.  That was some debugging code that snuck in there.  I'm removing it entirely.

2021-06-09 09:31 UTC, rprospero commented on src/classes/partialset.cpp
> +            auto nPoints = parser.argi(0);
I've added a block to reserve the space for all the terms.

2021-06-09 09:33 UTC, rprospero commented on src/classes/partialset.cpp
> +                argIndex = readDataPoint(argIndex, parser, unbound);
That is clearer.

2021-06-10 08:01 UTC, trisyoungs approved these changes

2021-06-10 09:39 UTC, merged