Open recent implementation
disorderedmaterials/dissolve pull request #778
Opened 2021-08-16 11:06 UTC by EthanDevlinSTFC

Fully implemented open recent menu

2021-08-16 14:46 UTC, trisyoungs requested changes
Overall very good - organisation of code, use of `auto` etc.  Just a few small suggestions/changes to address.

2021-08-16 14:46 UTC, trisyoungs commented on src/gui/gui.ui
> +  </action>
Randomly-named action?

2021-08-16 14:46 UTC, trisyoungs commented on src/gui/gui.h
> +    const int recentFileNo;
For us, private member variables always have a suffixed underscore:
```suggestion
    QList<QAction *> recentFileActionList_;
    const int recentFileNo_;
```

2021-08-16 14:46 UTC, trisyoungs commented on src/gui/gui.h
> +    void adjustForCurrentFile(const QString &filePath);
This function could be renamed to more clearly reflect what it's acting on - `addCurrentToRecentFiles` for instance.

2021-08-16 14:46 UTC, trisyoungs commented on src/gui/gui_funcs.cpp
> +    : QMainWindow(nullptr), dissolve_(dissolve), threadController_(this, dissolve), recentFileNo(4)
Four is a bit stingy!  Perhaps 10 as the default?

2021-08-16 14:46 UTC, trisyoungs commented on src/gui/gui_funcs.cpp
> +        QString strippedName = QFileInfo(recentFilePaths.at(i)).fileName();
I have a lot of input files called the same thing, so I can't distinguish between them based on just the filename. You could add the full path after the filename in the menu - e.g. `input.txt (/home/tris/work/stuff/input.txt)` for example.

2021-08-16 14:46 UTC, trisyoungs commented on src/gui/gui_funcs.cpp
> +}
```suggestion
    // Fill recent menu
    for (auto i = 0u; i < recentFileNo; ++i)
    {
        if (i < recentFilePaths.size())
        {
            QString strippedName = QFileInfo(recentFilePaths.at(i)).fileName();
            recentFileActionList.at(i)->setText(strippedName);
            recentFileActionList.at(i)->setData(recentFilePaths.at(i));
            recentFileActionList.at(i)->setVisible(true);
        }
        else
            recentFileActionList.at(i)->setVisible(false);
    }
}
```

2021-08-16 14:49 UTC, EthanDevlinSTFC commented on src/gui/gui.ui
> +  </action>
Stray code, issue resolved

2021-08-16 14:49 UTC, trisyoungs commented
One further observation from testing the code - the font for the recent files actions is the default 11 pt, whereas all of the other menus are set to 10 pt.  Annoyingly, The submenu doesn't seem to inherit the font from its parent, so you'll have to set it manually (you can copy the font of the parent item and set that on your new menu).

2021-08-16 14:58 UTC, trisyoungs commented on src/gui/gui.h
> +    void adjustForCurrentFile(const QString &filePath);
Actually - the code doesn't really make use of the private member variable containing the current file because you're passing that as an argument, so even my suggested name is a touch misleading!  Perhaps simply `addRecentFile` would be enough?

2021-08-17 09:13 UTC, rprospero requested changes
A couple of small suggestions

2021-08-17 09:13 UTC, rprospero commented on src/gui/menu_file.cpp
> +                                                     "Dissolve input files (All files (*.*);;Text Files (*.txt))");
```suggestion
                                                     "Dissolve input files (*.txt);;All Files (*.*)");
```

I would suggest defaulting to the filtered view and letting the users choose an unfiltered one, instead of the other way around.

2021-08-17 15:36 UTC, trisyoungs commented on src/gui/menu_file.cpp
> +                                                     "Dissolve input files (*.txt;;All Extensions (*.*);;All Files (*))");
This is starting to get a bit messy now IMO. I don't think I've ever seen an option to choose between all files with/without extensions in a file dialog.  Question - if you remove the filter argument completely from the call to `getOpenFileName` do we just get "all files"?

2021-08-17 15:53 UTC, EthanDevlinSTFC commented on src/gui/menu_file.cpp
> +                                                     "Dissolve input files (*.txt;;All Extensions (*.*);;All Files (*))");
Removing the argument seems to disable all files. 
The issue with messiness is the use of file name over file type. I could modify the save functions to ensure all files are saved as "name".txt, or we can try to change how the function operates? 
I'm not sure how else we'd manage files without an explicit extension.
The simplest change would be to just have (*) be the only parameter and let the program handle invalid input files as it does already. Though, this would make for a messy file interface.

2021-08-18 13:11 UTC, trisyoungs approved these changes
Two small adjustments to make to keep the project manager happy, then this can be merged in.

2021-08-18 13:11 UTC, trisyoungs commented on src/gui/menu_file.cpp
> +                                                     "Dissolve input files (Text files (*.txt);;All Files (*))");
There's some odd bracketing going on here!  The second part of the line should read:
```
"Dissolve Input Files (*.txt);;All Files (*)");
```

2021-08-19 08:35 UTC, merged