Array index iteration implementation
disorderedmaterials/dissolve pull request #792
Opened 2021-09-02 15:45 UTC by EthanDevlinSTFC

Full solution and implementation of raw index based iteration of multi-dimensional arrays.
closes #771

2021-09-03 10:12 UTC, trisyoungs requested changes
This is all good, however I think there are some nice simplifications that can be made. It would be good to get @rprospero 's opinion on some of my comments here.

Also, this is crying out for a unit test!

2021-09-03 10:12 UTC, trisyoungs commented on src/math/data3d.cpp
> +        while (index++.hasNext())
I find this notation a bit "opaque" in terms of its logic.  Does the `ArrayIndex3D` class permit the use of constructions like `for (auto id : index)` as well?

2021-09-03 10:12 UTC, trisyoungs commented on src/math/data3d.cpp
> +            errors_[*index] = parser.argd(1);
Dereferencing to get the tuple is a bit raw IMO.  Could perhaps define a conversion operator allowing implicit conversion of the index to a `std::tuple<int,int,int>`?

2021-09-03 10:12 UTC, trisyoungs commented on src/templates/arrayIndex2d.h
> +#include <vector>
Most of these includes are redundant:
```suggestion
#include <tuple>
```

2021-09-03 10:12 UTC, trisyoungs commented on src/templates/arrayIndex2d.h
> +        return arrayIndex;
```suggestion
        return {rawIndex / nY_, rawIndex % nY_};
```

2021-09-03 10:12 UTC, trisyoungs commented on src/templates/arrayIndex2d.h
> +    const double *ptr_;
Assuming that this is a `double` will break the class for any array that contains other objects.  Does the `ptr_` member really need to be a pointer at all? It's only used to determine the raw index, so could just be a straight `int`.  Extending this, does the reference to the array even need to be stored?  All we need to do is generate indices over some range - the underlying array itself is kinda irrelevant.

2021-09-03 10:12 UTC, trisyoungs commented on src/templates/arrayIndex3d.h
> +#include <vector>
```suggestion
#include <tuple>
```

2021-09-03 10:12 UTC, trisyoungs commented on src/templates/arrayIndex3d.h
> +        return arrayIndex;
```suggestion
        return {rawIndex / (nY_ * nZ_), rawIndex % nY_ / nZ_, rawIndex % nY_ % nZ_};
```

2021-09-03 10:12 UTC, trisyoungs commented on src/templates/arrayIndex3d.h
> +    const double *ptr_;
Same here.

2021-09-22 13:19 UTC, rprospero requested changes
I think we're getting closer to where we want to be

2021-09-22 13:19 UTC, rprospero commented on src/math/data2d.cpp
> +        while (index++.hasNext())
Using the `while` loop and our own `hasNext` method is a bit fragile.  It would be better if we could treat this like a standard for loop.  It should look something more like

```suggestion
        for (auto index : ArrayIndex2D(values_))
```

This also offers the coder the option of 

```suggestion
        for (auto &[x, y] : ArrayIndex2D(values_))
```

for when the individual coordinates are more significant (which they are not, in this instance).

2021-09-22 13:19 UTC, rprospero commented on src/math/data2d.cpp
> +            errors_[*index] = parser.argd(1);
With my changes suggested above, we get a little cleaner code here
```suggestion
            values_[index] = parser.argd(0);
            errors_[index] = parser.argd(1);
```

2021-09-22 13:19 UTC, rprospero commented on src/math/data2d.cpp
> +            values_[*index] = parser.argd(0);
Same comments as above

2021-09-22 13:19 UTC, rprospero commented on src/math/data2d.cpp
> +                return false;
Same as above

2021-09-22 13:19 UTC, rprospero commented on src/math/data2d.cpp
> +                return false;
Same as above

2021-09-22 13:19 UTC, rprospero commented on src/math/data3d.cpp
> +        while (index++.hasNext())
Hopefully, my suggestion will fix that opacity.

2021-09-22 13:19 UTC, rprospero commented on src/math/data3d.cpp
> +            errors_[*index] = parser.argd(1);
Implementing my suggested course should remove the need for the dereference.

2021-09-22 13:19 UTC, rprospero commented on src/templates/arrayIndex2d.h
> +    }
You'll probably want another constructor so that you can create indices at arbitrary parts of the array, and not just at {0, 0}

2021-09-22 13:19 UTC, rprospero commented on src/templates/arrayIndex2d.h
> +    const double *ptr_;
Agreed.  We only ever care about the index, so it doesn't need to be a pointer and we don't need the refrence to the raw array.  This also means that the class can be used for iteration where there isn't necessarily an underlying Array2D.

2021-09-22 13:19 UTC, rprospero commented on src/templates/arrayIndex2d.h
> +    std::tuple<int, int> end() { return std::make_tuple(nX_, nY_); }
For the range-based `for` loops and algorithms to work properly, these really should return `ArrayIndex` instances.  `begin` should have an index of zero and `end` should have an index equal to the size of the array.  You'll need to correct this if you're going to use my suggestions.

2021-09-22 13:19 UTC, rprospero commented on src/templates/arrayIndex2d.h
> +
If we have proper bounding iterators to compare against (i.e. `begin` and `end`), then we shouldn't need this class.  I'm also a little concerned about the logic on this.  For a 3x3 array, wouldn't `{nX_, nY_}` be `{3, 3}`, but our final array element would be `{2, 2}`?

2021-11-01 11:00 UTC, rprospero commented
I noticed this morning that the unit tests won't actually run.  You'll need to add

```
dissolve_unit_test(arrayIteration.cpp)
```

to the end of `unit/algorithms/CMakeLists.txt`

2021-11-05 13:35 UTC, merged