Remove list dependency from Procedure Node
disorderedmaterials/dissolve pull request #876
Opened 2021-11-18 17:36 UTC by rprospero

This should remove the last dependency on the old List container

2021-11-19 11:44 UTC, rprospero commented
This PR now completely removes the the List template.  It also removes the `SelectForcefieldDialog`, since it depended on the List class and didn't seem to be used anywhere.

2021-11-23 15:55 UTC, trisyoungs requested changes
Requested changes only because there's a fix for the failing CI in my comments. Otherwise looks OK.

I note that there's around a 10% performance penalty when running analysis-heavy stuff (tested with the `calculate_dangle` system test) because of the move to `std::ahared_ptr`s here. Not a job for right now, but we might be able to reclaim that in the hot loops by getting and using the raw pointer reference temporarily, rather than suffer the cost of indirection each time.

2021-11-23 15:55 UTC, trisyoungs commented on src/gui/models/procedureNodeModel.cpp
> +Q_DECLARE_METATYPE(ConstNodeRef);
No longer necessary?
```suggestion
```

2021-11-23 15:55 UTC, trisyoungs commented on src/keywords/dynamicsitenodes.cpp
> +    auto dynamicSite = std::dynamic_pointer_cast<DynamicSiteProcedureNode>(parentNode_->shared_from_this());
This fixes the error in the CI for the `calculate_dangle` test.
```suggestion
    auto dynamicSite = std::make_shared<DynamicSiteProcedureNode>(
        std::dynamic_pointer_cast<SelectProcedureNode>(parentNode_->shared_from_this()));
```

2021-11-29 12:16 UTC, trisyoungs commented
Before my PRs cause this PR any more grief, I suggest that you merge in once the conflicts are fixed _before_ #879 - I'll then deal with the merge conflicts that result from all my moving of files about.

2021-11-29 14:36 UTC, merged