Add a proper model for the procedure nodes
disorderedmaterials/dissolve pull request #963
Opened 2022-01-31 11:51 UTC by rprospero

This adds a proper, recursive tree model for the procedure nodes.  It's currently only used for the generators, but it can also later be used for analysis nodes.  This includes adding a `parent` and `child` function to the procedure nodes to more easily enable navigating the structure.

2022-01-31 12:12 UTC, rprospero commented
This PR also includes a small change to the build system of the unit test setup.  Tests are now only linked against the gui parts of dissolve if they are, in fact, testing gui components.  This prevents unit tests from being repeatedly recompiled and linked when nothing has changed within them or their dependencies.

2022-02-02 12:26 UTC, trisyoungs requested changes
An excellent solution to the problem.

I have one comment to make on the variance of the `children()` functions, and a small change to request. The `ProcedureGroup` `QGroupBox` containing the keywords widget always has the title `ProcedureNode` - this should really be the node type followed by the explicit name of the node in parentheses if it has one.

2022-02-02 12:26 UTC, trisyoungs commented on src/procedure/nodes/process1d.cpp
> +    return {};
Perhaps I'm missing something here, but why does this particular branch need an explicit cast where in other nodes (e.g. `Collect1D`) it doesn't?

2022-02-02 12:26 UTC, trisyoungs commented on src/procedure/nodes/process2d.cpp
> +    return {};
And here.

2022-02-02 12:26 UTC, trisyoungs commented on src/procedure/nodes/select.cpp
> +std::vector<ConstNodeRef> SelectProcedureNode::children() const { return {forEachBranch_}; }
No cast here, but in other places there is an `if`/`else` clause.  Can all of the `children()` functions be similar to this one?

2022-02-07 09:32 UTC, merged