Replace Lists with Vectors
disorderedmaterials/dissolve pull request #970
Opened 2022-02-10 13:14 UTC by IVlaD17

Closes #619 

Pretty much what's being said in the title. Replacing `std::lists` with `std::vectors` where possible.

Changed the following areas:
- `data1dstore.h`
- `data2dstore.h`
- `data3dstore.h`
- `combopopulator.h`
- `tablewidgetupdater.h`
- `treewidgetupdater.h`

2022-03-08 09:15 UTC, trisyoungs requested changes
Looks good.  Some comments over a few of the loops which should be investigated.

2022-03-08 09:15 UTC, trisyoungs commented on src/classes/data1dstore.cpp
> +           data_.end()->get();
This doesn't look right and wouldn't traverse the vector:
```suggestion
    return std::find_if(data_.begin(), data_.end(), [&name](auto &data) { return data->first.tag() == name; }) !=
           data_.end();
```

2022-03-08 09:15 UTC, trisyoungs commented on src/classes/data1dstore.cpp
> +    if (it == data_.end()->get())
Same here:
```suggestion
    auto it = std::find_if(data_.begin(), data_.end(), [&name](auto &data) { return data->first.tag() == name; });
    if (it == data_.end())
```

2022-03-08 09:15 UTC, trisyoungs commented on src/classes/data2dstore.cpp
> +           data_.end()->get();
```suggestion
    auto it = std::find_if(data_.begin(), data_.end(), [&name](auto &data) { return data->first.tag() == name; });
    if (it == data_.end())
```

2022-03-08 09:15 UTC, trisyoungs commented on src/classes/data2dstore.cpp
> +    if (it == data_.end()->get())
```suggestion
    auto it = std::find_if(data_.begin(), data_.end(), [&name](auto &data) { return data->first.tag() == name; });
    if (it == data_.end())
```

2022-03-08 09:15 UTC, trisyoungs commented on src/classes/data3dstore.cpp
> +    if (it == data_.end()->get())
```suggestion
    auto it = std::find_if(data_.begin(), data_.end(), [&name](auto &data) { return data->first.tag() == name; });
    if (it == data_.end())
```

2022-03-08 09:15 UTC, trisyoungs commented on src/keywords/data1dstore.cpp
> +    for (const auto sharedDataPointer : data_.data())
Just a small thing, but we can avoid copying the shared pointer here and use a reference:
```suggestion
    for (const auto &sharedDataPointer : data_.data())
```

2022-03-08 09:15 UTC, trisyoungs commented on src/keywords/data2dstore.cpp
> +    for (const auto sharedDataPointer : data_.data())
```suggestion
    for (const auto &sharedDataPointer : data_.data())
```

2022-03-08 09:15 UTC, trisyoungs commented on src/modules/datatest/process.cpp
> +    for (auto sharedDataPointer : test1DData_.data())
```suggestion
    for (auto &sharedDataPointer : test1DData_.data())
```

2022-03-08 09:15 UTC, trisyoungs commented on src/modules/datatest/process.cpp
> +    for (auto sharedDataPointer : test2DData_.data())
```suggestion
    for (auto &sharedDataPointer : test2DData_.data())
```

2022-03-08 09:15 UTC, trisyoungs commented on src/modules/rdf/functions.cpp
> +    for (auto sharedDataPointer : testData.data())
```suggestion
    for (auto &sharedDataPointer : testData.data())
```

2022-03-08 10:15 UTC, rprospero commented
I agree with Tristan's comments, but otherwise approve.

2022-03-10 09:35 UTC, trisyoungs approved these changes

2022-03-10 09:36 UTC, merged